[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --tb=short --nomigrations
markers =
    asyncio: marks tests as async (pytest-asyncio)
    django_db: marks tests as using the database (pytest-django)

# pytest-asyncio configuration
asyncio_mode = auto
