# Generated by Django 5.2.11 on 2026-08-15 21:11

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "registro_id",
                    models.CharField(
                        max_length=4,
                        unique=True,
                        verbose_name="ID de Registro del Capítulo",
                    ),
                ),
                (
                    "abreviacion",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Abreviación del Capítulo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre del Capítulo"
                    ),
                ),
                (
                    "grupo_envio_intitucional",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Grupo de Envío Institucional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capítulo",
                "verbose_name_plural": "Capítulos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EspecialidadRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=50, unique=True, verbose_name="Slug"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad de Revisión",
                "verbose_name_plural": "Especialidades de Revisión",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="¿Es Staff?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Está Activo?"),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="DNI como identificador de login.",
                        max_length=8,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_dni",
                                message="El DNI debe contener exactamente 8 dígitos numéricos.",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="Nombre de usuario",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        help_text="8 dígitos numéricos exactamente.",
                        max_length=8,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_dni",
                                message="El DNI debe contener exactamente 8 dígitos numéricos.",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="DNI",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EspecialidadIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="especialidades",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad de Ingeniero",
                "verbose_name_plural": "Especialidades de Ingenieros",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCapitulo",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "registro_id",
                    models.CharField(
                        db_index=True,
                        max_length=4,
                        verbose_name="ID de Registro del Capítulo",
                    ),
                ),
                (
                    "abreviacion",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Abreviación del Capítulo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Nombre del Capítulo",
                    ),
                ),
                (
                    "grupo_envio_intitucional",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Grupo de Envío Institucional",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Capítulo",
                "verbose_name_plural": "historical Capítulos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidadIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidad de Ingeniero",
                "verbose_name_plural": "historical Especialidades de Ingenieros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidadRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "slug",
                    models.CharField(db_index=True, max_length=50, verbose_name="Slug"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidad de Revisión",
                "verbose_name_plural": "historical Especialidades de Revisión",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPerfilIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=100, verbose_name="Apellido Paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(max_length=100, verbose_name="Apellido Materno"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Género"
                    ),
                ),
                (
                    "cip",
                    models.CharField(
                        db_index=True,
                        help_text="Número de CIP del ingeniero.",
                        max_length=20,
                        verbose_name="CIP",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        db_index=True,
                        help_text="DNI del ingeniero (8 dígitos).",
                        max_length=8,
                        verbose_name="DNI",
                    ),
                ),
                (
                    "correo_personal",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Personal",
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Institucional",
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "ubigeo",
                    models.CharField(
                        blank=True,
                        help_text="Código de ubigeo del lugar de residencia.",
                        max_length=6,
                        null=True,
                        verbose_name="Ubigeo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo Profesional",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.especialidadingeniero",
                        verbose_name="Especialidad Profesional",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Perfil Ingeniero",
                "verbose_name_plural": "historical Perfiles Ingenieros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUsuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="¿Es Staff?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Está Activo?"),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellido"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=255, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="DNI como identificador de login.",
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_dni",
                                message="El DNI debe contener exactamente 8 dígitos numéricos.",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="Nombre de usuario",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="8 dígitos numéricos exactamente.",
                        max_length=8,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_dni",
                                message="El DNI debe contener exactamente 8 dígitos numéricos.",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="DNI",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Usuario",
                "verbose_name_plural": "historical Usuarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PerfilIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=100, verbose_name="Apellido Paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(max_length=100, verbose_name="Apellido Materno"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Género"
                    ),
                ),
                (
                    "cip",
                    models.CharField(
                        help_text="Número de CIP del ingeniero.",
                        max_length=20,
                        unique=True,
                        verbose_name="CIP",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        help_text="DNI del ingeniero (8 dígitos).",
                        max_length=8,
                        unique=True,
                        verbose_name="DNI",
                    ),
                ),
                (
                    "correo_personal",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Personal",
                    ),
                ),
                (
                    "correo_institucional",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Correo Institucional",
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "ubigeo",
                    models.CharField(
                        blank=True,
                        help_text="Código de ubigeo del lugar de residencia.",
                        max_length=6,
                        null=True,
                        verbose_name="Ubigeo",
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingenieros",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo Profesional",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingenieros",
                        to="usuarios.especialidadingeniero",
                        verbose_name="Especialidad Profesional",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_ingeniero",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Ingeniero",
                "verbose_name_plural": "Perfiles Ingenieros",
                "ordering": ["apellido_paterno", "apellido_materno", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="IngenieroHabilitacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "ultimo_periodo_pagado_cip",
                    models.CharField(
                        blank=True,
                        help_text="Último período pagado según CIP.",
                        max_length=20,
                        null=True,
                        verbose_name="Último Período Pagado CIP",
                    ),
                ),
                (
                    "condicion_cip",
                    models.CharField(
                        blank=True,
                        help_text="Condición del ingeniero según CIP (ej. '1' = habilitado).",
                        max_length=10,
                        null=True,
                        verbose_name="Condición CIP",
                    ),
                ),
                (
                    "fecha_busqueda",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha de la búsqueda (deduplicación diaria: 1 registro por CIP por día).",
                        null=True,
                        verbose_name="Fecha de Búsqueda",
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilitacion",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalIngenieroHabilitacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "ultimo_periodo_pagado_cip",
                    models.CharField(
                        blank=True,
                        help_text="Último período pagado según CIP.",
                        max_length=20,
                        null=True,
                        verbose_name="Último Período Pagado CIP",
                    ),
                ),
                (
                    "condicion_cip",
                    models.CharField(
                        blank=True,
                        help_text="Condición del ingeniero según CIP (ej. '1' = habilitado).",
                        max_length=10,
                        null=True,
                        verbose_name="Condición CIP",
                    ),
                ),
                (
                    "fecha_busqueda",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Fecha de la búsqueda (deduplicación diaria: 1 registro por CIP por día).",
                        null=True,
                        verbose_name="Fecha de Búsqueda",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ingeniero habilitacion",
                "verbose_name_plural": "historical ingeniero habilitacions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="especialidadingeniero",
            constraint=models.UniqueConstraint(
                fields=("codigo", "capitulo"),
                name="unique_especialidad_ingeniero_codigo_capitulo",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingenierohabilitacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fecha_busqueda__isnull", False)),
                fields=("perfil_ingeniero", "fecha_busqueda"),
                name="unique_perfil_fecha_busqueda",
            ),
        ),
    ]
