# Generated by Django 5.2.12 on 2026-08-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="especialidadrevision",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="historicalespecialidadrevision",
            name="codigo",
        ),
    ]
