# Generated by Django 5.2.11 on 2026-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingenierohabilitacion",
            name="fecha_busqueda",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Fecha de la búsqueda (deduplicación diaria: 1 registro por CIP por día).",
                null=True,
                verbose_name="Fecha de Búsqueda",
            ),
        ),
        migrations.AddField(
            model_name="ingenierohabilitacion",
            name="fecha_busqueda",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Fecha de la búsqueda (deduplicación diaria: 1 registro por CIP por día).",
                null=True,
                verbose_name="Fecha de Búsqueda",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingenierohabilitacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fecha_busqueda__isnull", False)),
                fields=("perfil_ingeniero", "fecha_busqueda"),
                name="unique_perfil_fecha_busqueda",
            ),
        ),
    ]
