# Generated by Django 5.2.11 on 2026-10-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperfilingeniero",
            name="dni",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="DNI del ingeniero (8 dígitos). Nullable para ingenieros extranjeros.",
                max_length=8,
                null=True,
                verbose_name="DNI",
            ),
        ),
        migrations.AlterField(
            model_name="perfilingeniero",
            name="dni",
            field=models.CharField(
                blank=True,
                help_text="DNI del ingeniero (8 dígitos). Nullable para ingenieros extranjeros.",
                max_length=8,
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
    ]
