# Generated by Django 5.2.12 on 2026-06-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='abreviacion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Abreviación del Capítulo'),
        ),
        migrations.AlterField(
            model_name='historicalcapitulo',
            name='abreviacion',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Abreviación del Capítulo'),
        ),
    ]
