# Generated by Django 5.2.11 on 2026-09-04 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_codigo_especialidad_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusuario",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Nombre de usuario para login (letras minúsculas, números, puntos, guiones bajos o guiones).",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="El nombre de usuario debe contener solo letras minúsculas, números, puntos, guiones bajos o guiones.",
                        regex="^[a-z0-9._-]+$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                help_text="Nombre de usuario para login (letras minúsculas, números, puntos, guiones bajos o guiones).",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="El nombre de usuario debe contener solo letras minúsculas, números, puntos, guiones bajos o guiones.",
                        regex="^[a-z0-9._-]+$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
    ]
