# Generated by Django 5.2.11 on 2026-06-12 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusuario",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="DNI como identificador de login.",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_dni",
                        message="El DNI debe contener exactamente 8 dígitos numéricos.",
                        regex="^\\d{8}$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                help_text="DNI como identificador de login.",
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_dni",
                        message="El DNI debe contener exactamente 8 dígitos numéricos.",
                        regex="^\\d{8}$",
                    )
                ],
                verbose_name="Nombre de usuario",
            ),
        ),
    ]
