# Generated by Django 5.2.11 on 2026-08-12 18:46

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_add_fecha_busqueda_to_ingeniero_habilitacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EspecialidadRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=50, unique=True, verbose_name="Slug"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad de Revisión",
                "verbose_name_plural": "Especialidades de Revisión",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EspecialidadIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="especialidades",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad de Ingeniero",
                "verbose_name_plural": "Especialidades de Ingenieros",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="historicalperfilingeniero",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadingeniero",
                verbose_name="Especialidad Profesional",
            ),
        ),
        migrations.AlterField(
            model_name="perfilingeniero",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingenieros",
                to="usuarios.especialidadingeniero",
                verbose_name="Especialidad Profesional",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidadIngeniero",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.capitulo",
                        verbose_name="Capítulo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidad de Ingeniero",
                "verbose_name_plural": "historical Especialidades de Ingenieros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidadRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=4, verbose_name="Código de Especialidad"
                    ),
                ),
                (
                    "slug",
                    models.CharField(db_index=True, max_length=50, verbose_name="Slug"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de Especialidad"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidad de Revisión",
                "verbose_name_plural": "historical Especialidades de Revisión",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="HistoricalEspecialidad",
        ),
        migrations.AddConstraint(
            model_name="especialidadingeniero",
            constraint=models.UniqueConstraint(
                fields=("codigo", "capitulo"),
                name="unique_especialidad_ingeniero_codigo_capitulo",
            ),
        ),
    ]
