# Generated by Django 5.2.11 on 2026-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_historicalusuario_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalperfilingeniero",
            name="condicion_cip",
            field=models.CharField(
                blank=True,
                help_text="Condición del ingeniero según CIP (ej. '1' = habilitado).",
                max_length=10,
                null=True,
                verbose_name="Condición CIP",
            ),
        ),
        migrations.AddField(
            model_name="historicalperfilingeniero",
            name="fecha_validacion_cip",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la última validación con el servicio CIP.",
                null=True,
                verbose_name="Fecha Validación CIP",
            ),
        ),
        migrations.AddField(
            model_name="historicalperfilingeniero",
            name="habilitado_cip",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el ingeniero está habilitado según CIP (último estado conocido).",
                verbose_name="Habilitado CIP",
            ),
        ),
        migrations.AddField(
            model_name="historicalperfilingeniero",
            name="ultimo_periodo_pagado_cip",
            field=models.CharField(
                blank=True,
                help_text="Último período pagado según CIP.",
                max_length=20,
                null=True,
                verbose_name="Último Período Pagado CIP",
            ),
        ),
        migrations.AddField(
            model_name="perfilingeniero",
            name="condicion_cip",
            field=models.CharField(
                blank=True,
                help_text="Condición del ingeniero según CIP (ej. '1' = habilitado).",
                max_length=10,
                null=True,
                verbose_name="Condición CIP",
            ),
        ),
        migrations.AddField(
            model_name="perfilingeniero",
            name="fecha_validacion_cip",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha/hora de la última validación con el servicio CIP.",
                null=True,
                verbose_name="Fecha Validación CIP",
            ),
        ),
        migrations.AddField(
            model_name="perfilingeniero",
            name="habilitado_cip",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el ingeniero está habilitado según CIP (último estado conocido).",
                verbose_name="Habilitado CIP",
            ),
        ),
        migrations.AddField(
            model_name="perfilingeniero",
            name="ultimo_periodo_pagado_cip",
            field=models.CharField(
                blank=True,
                help_text="Último período pagado según CIP.",
                max_length=20,
                null=True,
                verbose_name="Último Período Pagado CIP",
            ),
        ),
    ]
