# Generated by Django 5.2.11 on 2026-08-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0018_alter_historicalliquidacionespecialidaddisponibles_especialidad_and_more",
        ),
        ("usuarios", "0003_especialidadrevision_especialidadingeniero_and_more"),
        ("usuarios", "0003_1_copy_especialidad_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Especialidad",
        ),
    ]
