# Generated by Django 5.2.11 on 2026-09-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_update_usuario_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalusuario",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Correo electrónico",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Correo electrónico",
            ),
        ),
    ]
