# Generated by Django 5.2.12 on 2026-06-09 02:47

import django.db.models.deletion
import modules.liquidaciones.domain.validators
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDelegado',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado')),
                ('distrito', models.CharField(help_text='Distrito donde opera el delegado (validado contra ubigeo nacional).', max_length=200, validators=[modules.liquidaciones.domain.validators.validate_distrito], verbose_name='Distrito')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Delegado',
                'verbose_name_plural': 'historical Delegados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIgv',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje IGV')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical IGV',
                'verbose_name_plural': 'historical IGV',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLiquidacion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('valor_obra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de la Liquidación')),
                ('derecho_minimo', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Derecho Mínimo')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Porcentaje Aplicado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Liquidación',
                'verbose_name_plural': 'historical Liquidaciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProyectista',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Proyectista',
                'verbose_name_plural': 'historical Proyectistas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRevision',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('numero', models.PositiveIntegerField(help_text='Número secuencial de revisión por liquidación.', max_length=1, verbose_name='Número de Revisión')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Revisión',
                'verbose_name_plural': 'historical Revisiones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUit',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje UIT')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical UIT',
                'verbose_name_plural': 'historical UIT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Igv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje IGV')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'IGV',
                'verbose_name_plural': 'IGV',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('valor_obra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de la Liquidación')),
                ('derecho_minimo', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Derecho Mínimo')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Porcentaje Aplicado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyectista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Proyectista',
                'verbose_name_plural': 'Proyectistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('numero', models.PositiveIntegerField(help_text='Número secuencial de revisión por liquidación.', max_length=1, verbose_name='Número de Revisión')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
                'ordering': ['liquidacion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Uit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje UIT')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
            ],
            options={
                'verbose_name': 'UIT',
                'verbose_name_plural': 'UIT',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('especialidad', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado')),
                ('distrito', models.CharField(help_text='Distrito donde opera el delegado (validado contra ubigeo nacional).', max_length=200, validators=[modules.liquidaciones.domain.validators.validate_distrito], verbose_name='Distrito')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegados', to='entidades.banco', verbose_name='Banco')),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegados', to='entidades.municipalidad', verbose_name='Municipalidad')),
            ],
            options={
                'verbose_name': 'Delegado',
                'verbose_name_plural': 'Delegados',
                'ordering': ['perfil_ingeniero__apellido_paterno', 'perfil_ingeniero__apellido_materno'],
            },
        ),
    ]
