# Generated by Django 5.2.11 on 2026-06-18 11:25

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("finanzas", "0002_delete_derechominimo_delete_historicalderechominimo"),
        ("usuarios", "0003_alter_historicalusuario_username_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EdificacionesTarifa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "porcentaje_minimo_uit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje del UIT que define el derecho mínimo.",
                        max_digits=5,
                        verbose_name="Porcentaje Mínimo UIT",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto mínimo de derecho.",
                        max_digits=10,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Monto máximo de derecho (opcional).",
                        max_digits=10,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de Edificación",
                "verbose_name_plural": "Tarifas de Edificaciones",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Nombre de la Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.CreateModel(
            name="Proyectista",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "cip",
                    models.CharField(
                        blank=True,
                        help_text="Número de CIP (6 dígitos).",
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="CIP",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        help_text="Número de DNI (8 dígitos).",
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="DNI",
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        blank=True,
                        help_text="Número de CAP (6 dígitos).",
                        max_length=6,
                        null=True,
                        verbose_name="CAP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyectista",
                "verbose_name_plural": "Proyectistas",
            },
        ),
        migrations.CreateModel(
            name="EdificacionesRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "porcentaje_liquidacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje aplicado para el cálculo del derecho.",
                        max_digits=5,
                        verbose_name="Porcentaje de Liquidación",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "tarifa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisiones",
                        to="liquidaciones.edificacionestarifa",
                        verbose_name="Tarifa de Edificación",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión de Edificación",
                "verbose_name_plural": "Revisiones de Edificaciones",
                "db_table": "liquidaciones_edificacionesrevision",
                "unique_together": {("tarifa", "especialidad")},
            },
        ),
        migrations.CreateModel(
            name="Delegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("titular", "Titular"), ("alterno", "Alterno")],
                        default="titular",
                        max_length=20,
                        verbose_name="Tipo de Delegado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegados",
                        to="entidades.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegado_liquidacion",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegados",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegado",
                "verbose_name_plural": "Delegados",
                "ordering": [
                    "perfil_ingeniero__apellido_paterno",
                    "perfil_ingeniero__apellido_materno",
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("titular", "Titular"), ("alterno", "Alterno")],
                        default="titular",
                        max_length=20,
                        verbose_name="Tipo de Delegado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Delegado",
                "verbose_name_plural": "historical Delegados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEdificacionesTarifa",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "porcentaje_minimo_uit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje del UIT que define el derecho mínimo.",
                        max_digits=5,
                        verbose_name="Porcentaje Mínimo UIT",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto mínimo de derecho.",
                        max_digits=10,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Monto máximo de derecho (opcional).",
                        max_digits=10,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarifa de Edificación",
                "verbose_name_plural": "historical Tarifas de Edificaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        verbose_name="Nombre de la Especialidad",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidad",
                "verbose_name_plural": "historical Especialidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMunicipalidadDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Municipalidad del Delegado",
                "verbose_name_plural": "historical Municipalidades de los Delegados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPeriodoDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Inicio del Periodo")),
                ("periodo_fin", models.DateField(verbose_name="Fin del Periodo")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Periodo del Delegado",
                "verbose_name_plural": "historical Periodos de los Delegados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProyectista",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("nombres", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "apellidos",
                    models.CharField(max_length=255, verbose_name="Apellidos"),
                ),
                (
                    "cip",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Número de CIP (6 dígitos).",
                        max_length=6,
                        null=True,
                        verbose_name="CIP",
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Número de DNI (8 dígitos).",
                        max_length=8,
                        null=True,
                        verbose_name="DNI",
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        blank=True,
                        help_text="Número de CAP (6 dígitos).",
                        max_length=6,
                        null=True,
                        verbose_name="CAP",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Proyectista",
                "verbose_name_plural": "historical Proyectistas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público del proyecto (ej. PROY-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "nombre_propietario",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Propietario"
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        max_length=255, verbose_name="Denominación del Proyecto"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Dirección del Proyecto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Proyecto"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.ubigeodistrito",
                        verbose_name="Distrito del Proyecto",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.entidad",
                        verbose_name="Entidad",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Proyecto",
                "verbose_name_plural": "historical Proyectos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("REINGRESADA", "Reingresada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Revisión",
                    ),
                ),
                (
                    "valor_proyecto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor de Obra"
                    ),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "igv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finanzas.igv",
                        verbose_name="IGV",
                    ),
                ),
                (
                    "liquidaciones_previas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Referencias a liquidaciones anteriores en caso de revisiones sucesivas.",
                        related_name="revisiones",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidaciones Previas",
                    ),
                ),
                (
                    "uit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finanzas.uit",
                        verbose_name="UIT",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="liquidaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación",
                "verbose_name_plural": "Liquidaciones",
                "ordering": ["proyecto", "-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="LiquidacionDocumentos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        upload_to="liquidaciones/documentos/",
                        verbose_name="Archivo del Documento",
                    ),
                ),
                (
                    "liquidacion_maestra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación Maestra",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalRevisionDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Revisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Delegado de Revisión",
                "verbose_name_plural": "historical Delegados de liquidaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionEdificaciones",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero_revision",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número secuencial de revisión por liquidación de edificaciones.",
                        verbose_name="Número de Revisión",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("AMPLIACION", "Ampliación"),
                            ("ESPECIALIDAD", "Especialidad"),
                            ("MODIFICACION", "Modificación de Licencia"),
                            ("PLANTAS_TIPICAS", "Plantas Típicas"),
                        ],
                        default="ESPECIALIDAD",
                        max_length=20,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Edificaciones",
                "verbose_name_plural": "historical Liquidaciones de Edificaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionDocumentos",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre_documento",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "documento",
                    models.TextField(
                        max_length=100, verbose_name="Archivo del Documento"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_maestra",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación Maestra",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical liquidacion documentos",
                "verbose_name_plural": "historical liquidacion documentoss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionEdificacionesProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación Edificación",
                "verbose_name_plural": "Liquidaciones Edificaciones",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Datos calculados de la liquidación en formato JSON.",
                        verbose_name="Datos del snapshot",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Liquidación",
                "verbose_name_plural": "Snapshots de Liquidación",
            },
        ),
        migrations.CreateModel(
            name="PeriodoDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Inicio del Periodo")),
                ("periodo_fin", models.DateField(verbose_name="Fin del Periodo")),
                (
                    "delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_asignados",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Periodo del Delegado",
                "verbose_name_plural": "Periodos de los Delegados",
                "ordering": [
                    "delegado__perfil_ingeniero__apellido_paterno",
                    "periodo_inicio",
                ],
            },
        ),
        migrations.CreateModel(
            name="LiquidacionEdificaciones",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero_revision",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número secuencial de revisión por liquidación de edificaciones.",
                        verbose_name="Número de Revisión",
                    ),
                ),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("AMPLIACION", "Ampliación"),
                            ("ESPECIALIDAD", "Especialidad"),
                            ("MODIFICACION", "Modificación de Licencia"),
                            ("PLANTAS_TIPICAS", "Plantas Típicas"),
                        ],
                        default="ESPECIALIDAD",
                        max_length=20,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                (
                    "revisiones",
                    models.ManyToManyField(
                        related_name="liquidaciones_edificaciones",
                        to="liquidaciones.edificacionesrevision",
                        verbose_name="Revisiones de Edificación",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edificaciones",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
                (
                    "proyectistas",
                    models.ManyToManyField(
                        related_name="liquidaciones_edificaciones",
                        to="liquidaciones.proyectista",
                        verbose_name="Proyectistas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Edificaciones",
                "verbose_name_plural": "Liquidaciones de Edificaciones",
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público del proyecto (ej. PROY-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "nombre_propietario",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Propietario"
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        max_length=255, verbose_name="Denominación del Proyecto"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Dirección del Proyecto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Proyecto"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proyectos",
                        to="entidades.ubigeodistrito",
                        verbose_name="Distrito del Proyecto",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos",
                        to="entidades.entidad",
                        verbose_name="Entidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["denominacion"],
            },
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones",
                to="liquidaciones.proyecto",
                verbose_name="Proyecto",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        blank=True, editable=False, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("REINGRESADA", "Reingresada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Revisión",
                    ),
                ),
                (
                    "valor_proyecto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor de Obra"
                    ),
                ),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "igv",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.igv",
                        verbose_name="IGV",
                    ),
                ),
                (
                    "uit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.uit",
                        verbose_name="UIT",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario Creador",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación",
                "verbose_name_plural": "historical Liquidaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProyectoEmpresarial",
            fields=[],
            options={
                "verbose_name": "Proyecto Empresarial",
                "verbose_name_plural": "Proyectos Empresariales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.proyecto",),
        ),
        migrations.CreateModel(
            name="ProyectoPersonaNatural",
            fields=[],
            options={
                "verbose_name": "Proyecto Persona Natural",
                "verbose_name_plural": "Proyectos Persona Natural",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.proyecto",),
        ),
        migrations.CreateModel(
            name="LiquidacionContacto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la liquidación.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la liquidación.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación - Contacto",
                "verbose_name_plural": "Liquidaciones - Contactos",
                "ordering": ["-principal", "liquidacion__proyecto__denominacion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liquidacion", "contacto"),
                        name="unique_liquidacion_contacto",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MunicipalidadDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distritos_asignados",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegados",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipalidad del Delegado",
                "verbose_name_plural": "Municipalidades de los Delegados",
                "ordering": [
                    "delegado__perfil_ingeniero__apellido_paterno",
                    "delegado__perfil_ingeniero__apellido_materno",
                    "municipalidad__nombre",
                ],
                "unique_together": {("delegado", "municipalidad")},
            },
        ),
        migrations.CreateModel(
            name="ContactoProyecto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal del proyecto.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en el proyecto.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="liquidaciones.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto - Contacto",
                "verbose_name_plural": "Proyectos - Contactos",
                "ordering": ["-principal", "proyecto__denominacion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proyecto", "contacto"), name="unique_proyecto_contacto"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RevisionDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidacion_delegados",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_delegados",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Revisión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegado de Revisión",
                "verbose_name_plural": "Delegados de liquidaciones",
                "ordering": ["liquidacion", "delegado"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liquidacion", "delegado"),
                        name="unique_liquidacion_delegado",
                    )
                ],
            },
        ),
    ]
