# Generated by Django 5.2.11 on 2026-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="delegados",
            field=models.ManyToManyField(
                related_name="liquidaciones_edificaciones",
                to="liquidaciones.delegado",
                verbose_name="Delegados",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Subtotal calculado de la liquidación . Se llena después del cálculo.",
                max_digits=12,
                null=True,
                verbose_name="Sub Total",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Subtotal calculado de la liquidación . Se llena después del cálculo.",
                max_digits=12,
                null=True,
                verbose_name="Sub Total",
            ),
        ),
    ]
