# Generated by Django 5.2.11 on 2026-06-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0001_initial"),
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proyectista",
            options={
                "ordering": ["nombres"],
                "verbose_name": "Proyectista",
                "verbose_name_plural": "Proyectistas",
            },
        ),
        migrations.RemoveField(
            model_name="historicalliquidacionedificaciones",
            name="clasificacion",
        ),
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="clasificacion",
        ),
        migrations.AddField(
            model_name="historicalliquidacionedificaciones",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identificador público de la liquidación de edificaciones (ej. LIQ-EDIF-2026-00001).",
                max_length=50,
                null=True,
                verbose_name="ID Público",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionedificaciones",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionedificaciones",
            name="tramite_accion",
            field=models.CharField(
                choices=[
                    ("PRIMERA_REVISION", "Primera Revisión"),
                    ("REVISION", "Revisión"),
                ],
                default="PRIMERA_REVISION",
                max_length=20,
                verbose_name="Acción de Trámite",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="municipalidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identificador público de la liquidación (ej. LIQ-2026-00001).",
                max_length=50,
                null=True,
                verbose_name="ID Público",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="public_id",
            field=models.CharField(
                blank=True,
                help_text="Identificador público de la liquidación de edificaciones (ej. LIQ-EDIF-2026-00001).",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="ID Público",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="tramite_accion",
            field=models.CharField(
                choices=[
                    ("PRIMERA_REVISION", "Primera Revisión"),
                    ("REVISION", "Revisión"),
                ],
                default="PRIMERA_REVISION",
                max_length=20,
                verbose_name="Acción de Trámite",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="municipalidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="public_id",
            field=models.CharField(
                blank=True,
                help_text="Identificador público de la liquidación (ej. LIQ-2026-00001).",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="ID Público",
            ),
        ),
    ]
