# Generated by Django 5.2.12 on 2026-06-09 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0002_initial'),
        ('liquidaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegado',
            name='perfil_ingeniero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delegado_liquidacion', to='usuarios.perfilingeniero', verbose_name='Perfil de Ingeniero'),
        ),
        migrations.AddField(
            model_name='historicaldelegado',
            name='banco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='historicaldelegado',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldelegado',
            name='municipalidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.municipalidad', verbose_name='Municipalidad'),
        ),
        migrations.AddField(
            model_name='historicaldelegado',
            name='perfil_ingeniero',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.perfilingeniero', verbose_name='Perfil de Ingeniero'),
        ),
        migrations.AddField(
            model_name='historicaligv',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalliquidacion',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalliquidacion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalproyectista',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrevision',
            name='delegado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.delegado', verbose_name='Delegado'),
        ),
        migrations.AddField(
            model_name='historicalrevision',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalliquidacion',
            name='igv',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.igv', verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='igv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='liquidaciones.igv', verbose_name='IGV'),
        ),
        migrations.AddField(
            model_name='historicalrevision',
            name='liquidacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.liquidacion', verbose_name='Liquidación'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='proyectista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='liquidaciones.proyectista', verbose_name='Proyectista'),
        ),
        migrations.AddField(
            model_name='historicalliquidacion',
            name='proyectista',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.proyectista', verbose_name='Proyectista'),
        ),
        migrations.AddField(
            model_name='revision',
            name='delegado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='liquidaciones.delegado', verbose_name='Delegado'),
        ),
        migrations.AddField(
            model_name='revision',
            name='liquidacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='liquidaciones.liquidacion', verbose_name='Liquidación'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='uit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='liquidaciones.uit', verbose_name='UIT'),
        ),
        migrations.AddField(
            model_name='historicalliquidacion',
            name='uit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.uit', verbose_name='UIT'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('liquidacion', 'numero'), name='unique_liquidacion_revision_numero'),
        ),
    ]
