# Generated by Django 5.2.12 on 2026-06-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrevision',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número secuencial de revisión por liquidación. Se asigna automáticamente si se omite.', verbose_name='Número de Revisión'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número secuencial de revisión por liquidación. Se asigna automáticamente si se omite.', verbose_name='Número de Revisión'),
        ),
    ]
