# Generated by Django 5.2.11 on 2026-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0002_liquidacionedificaciones_delegados_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperiododelegado",
            name="periodo_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fin del Periodo"
            ),
        ),
        migrations.AlterField(
            model_name="periododelegado",
            name="periodo_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fin del Periodo"
            ),
        ),
    ]
