# Generated by Django 5.2.11 on 2026-08-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inspectoroperacion",
            name="inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_liquidacion",
                to="liquidaciones.inspector",
                verbose_name="Inspector",
            ),
        ),
    ]
