# Generated by Django 5.2.12 on 2026-08-07 14:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarifaporcategoriavisitas",
            options={
                "ordering": ["tarifa_base__tipo_liquidacion", "porcentaje_uit"],
                "verbose_name": "Tarifa por Categoría de Visitas",
                "verbose_name_plural": "Tarifas por Categoría de Visitas",
            },
        ),
        migrations.RemoveField(
            model_name="historicalliquidaciongeneral",
            name="periodo_fin",
        ),
        migrations.RemoveField(
            model_name="historicalliquidaciongeneral",
            name="periodo_inicio",
        ),
        migrations.RemoveField(
            model_name="historicaltarifaporcategoriavisitas",
            name="costo_por_visita",
        ),
        migrations.RemoveField(
            model_name="liquidaciongeneral",
            name="periodo_fin",
        ),
        migrations.RemoveField(
            model_name="liquidaciongeneral",
            name="periodo_inicio",
        ),
        migrations.RemoveField(
            model_name="tarifaporcategoriavisitas",
            name="costo_por_visita",
        ),
        migrations.AddField(
            model_name="historicaltarifaporcategoriavisitas",
            name="porcentaje_uit",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Porcentaje de la UIT aplicable para esta categoría.",
                max_digits=10,
                verbose_name="% de UIT",
            ),
        ),
        migrations.AddField(
            model_name="tarifaporcategoriavisitas",
            name="porcentaje_uit",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Porcentaje de la UIT aplicable para esta categoría.",
                max_digits=10,
                verbose_name="% de UIT",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionporcategoriavisitas",
            name="liquidacion_general",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liquidacion_visitas",
                to="liquidaciones.liquidaciongeneral",
                verbose_name="Liquidación General",
            ),
        ),
    ]
