# Generated by Django 5.2.12 on 2026-08-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0003_alter_tarifaporcategoriavisitas_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltarifaporcategoriavisitas",
            name="categoria_visitas",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="Categoría de visitas según el tipo de trámite/acción.",
                max_length=50,
                verbose_name="Categoría de Visitas",
            ),
        ),
        migrations.AlterField(
            model_name="tarifaporcategoriavisitas",
            name="categoria_visitas",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                help_text="Categoría de visitas según el tipo de trámite/acción.",
                max_length=50,
                verbose_name="Categoría de Visitas",
            ),
        ),
    ]
