# Generated by Django 5.2.11 on 2026-08-15 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0003_alter_inspectoroperacion_inspector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegadooperacion",
            name="delegado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipalidades_asignadas",
                to="liquidaciones.delegado",
                verbose_name="Delegado",
            ),
        ),
    ]
