# Generated by Django 5.2.11 on 2026-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0003_alter_historicalperiododelegado_periodo_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmunicipalidaddelegado",
            name="tipo",
            field=models.CharField(
                choices=[("titular", "Titular"), ("alterno", "Alterno")],
                default="titular",
                max_length=20,
                verbose_name="Tipo de Delegado",
            ),
        ),
        migrations.AddField(
            model_name="municipalidaddelegado",
            name="tipo",
            field=models.CharField(
                choices=[("titular", "Titular"), ("alterno", "Alterno")],
                default="titular",
                max_length=20,
                verbose_name="Tipo de Delegado",
            ),
        ),
    ]
