# Generated by Django 5.2.11 on 2026-06-25 16:19

from django.db import migrations


def copy_tipo_to_municipalidad_delegado(apps, schema_editor):
    """Copy tipo from Delegado to each associated MunicipalidadDelegado record."""
    MunicipalidadDelegado = apps.get_model('liquidaciones', 'MunicipalidadDelegado')
    for md in MunicipalidadDelegado.objects.select_related('delegado').all():
        if md.delegado and hasattr(md.delegado, 'tipo') and md.delegado.tipo:
            md.tipo = md.delegado.tipo
            md.save(update_fields=['tipo'])


def reverse_copy(apps, schema_editor):
    """Reverse: no action needed, tipo will be removed from Delegado in separate migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0004_add_tipo_to_municipalidad_delegado"),
    ]

    operations = [
        migrations.RunPython(copy_tipo_to_municipalidad_delegado, reverse_copy),
    ]
