# Generated by Django 5.2.11 on 2026-08-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0004_alter_delegadooperacion_delegado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalliquidacioninspector",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Inspector de Liquidación de Inspección de Obra",
                "verbose_name_plural": "historical Inspectores de liquidaciones de Inspección de Obra",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidacioninspector",
            options={
                "ordering": ["liquidacion", "inspector"],
                "verbose_name": "Inspector de Liquidación de Inspección de Obra",
                "verbose_name_plural": "Inspectores de liquidaciones de Inspección de Obra",
            },
        ),
        migrations.AlterField(
            model_name="historicalliquidacioninspector",
            name="liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.liquidacioninspeccionobra",
                verbose_name="Liquidación de Inspección de Obra",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioninspector",
            name="liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspectores",
                to="liquidaciones.liquidacioninspeccionobra",
                verbose_name="Liquidación de Inspección de Obra",
            ),
        ),
    ]
