# Generated by Django 5.2.12 on 2026-06-09 13:56

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0004_alter_delegado_distrito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrevision',
            name='delegado',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='delegado',
        ),
        migrations.CreateModel(
            name='HistoricalRevisionDelegado',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('delegado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.delegado', verbose_name='Delegado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='liquidaciones.revision', verbose_name='Revisión')),
            ],
            options={
                'verbose_name': 'historical Delegado de Revisión',
                'verbose_name_plural': 'historical Delegados de Revisiones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RevisionDelegado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_delegados', to='liquidaciones.delegado', verbose_name='Delegado')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_delegados', to='liquidaciones.revision', verbose_name='Revisión')),
            ],
            options={
                'verbose_name': 'Delegado de Revisión',
                'verbose_name_plural': 'Delegados de Revisiones',
                'ordering': ['revision', 'delegado'],
                'constraints': [models.UniqueConstraint(fields=('revision', 'delegado'), name='unique_revision_delegado')],
            },
        ),
    ]
