# Generated by Django 5.2.11 on 2026-08-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0004_alter_historicaltarifaporcategoriavisitas_categoria_visitas_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionpormetrocuadrado",
            name="liquidacion_general",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liquidacion_m2",
                to="liquidaciones.liquidaciongeneral",
                verbose_name="Liquidación General",
            ),
        ),
    ]
