# Generated by Django 5.2.11 on 2026-06-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0005_copy_tipo_to_municipalidad_delegado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delegado",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="historicaldelegado",
            name="tipo",
        ),
    ]
