# Generated by Django 5.2.11 on 2026-08-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0005_alter_liquidacioninspector_fk_a_io"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="inspector",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="delegado",
            name="especialidad_revision",
        ),
        migrations.RemoveField(
            model_name="historicaldelegado",
            name="especialidad_revision",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="especialidad_revision",
        ),
    ]
