# Generated by Django 5.2.11 on 2026-08-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0005_alter_liquidacionpormetrocuadrado_liquidacion_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="uit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto de la Unidad Impositiva Tributaria (UIT) correspondiente.",
                max_digits=10,
                null=True,
                verbose_name="UIT",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionporcentajeobradetalle",
            name="uit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monto de la Unidad Impositiva Tributaria (UIT) correspondiente.",
                max_digits=10,
                null=True,
                verbose_name="UIT",
            ),
        ),
    ]
