# Generated by Django 5.2.11 on 2026-06-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0006_remove_tipo_from_delegado"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmunicipalidaddelegado",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edificaciones", "Edificaciones"),
                    ("Habilitaciones Urbanas", "Habilitaciones Urbanas"),
                ],
                max_length=50,
                null=True,
                verbose_name="Categoría del Delegado",
            ),
        ),
        migrations.AddField(
            model_name="municipalidaddelegado",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Edificaciones", "Edificaciones"),
                    ("Habilitaciones Urbanas", "Habilitaciones Urbanas"),
                ],
                max_length=50,
                null=True,
                verbose_name="Categoría del Delegado",
            ),
        ),
    ]
