# Generated by Django 5.2.11 on 2026-08-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0006_historicalliquidacionporcentajeobradetalle_uit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="derechoporcentajeobra",
            name="derecho_minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Monto mínimo absoluto del derecho en soles.",
                max_digits=10,
                null=True,
                verbose_name="Derecho Mínimo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalderechoporcentajeobra",
            name="derecho_minimo",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Monto mínimo absoluto del derecho en soles.",
                max_digits=10,
                null=True,
                verbose_name="Derecho Mínimo",
            ),
        ),
    ]
