# Generated by Django 5.2.11 on 2026-08-16 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0007_liquidacioninspector_especialidad_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidacioninspector",
            name="liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.liquidacionporcategoriavisitas",
                verbose_name="Liquidación por Categoría de Visitas",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioninspector",
            name="liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspectores",
                to="liquidaciones.liquidacionporcategoriavisitas",
                verbose_name="Liquidación por Categoría de Visitas",
            ),
        ),
    ]
