# Generated by Django 5.2.11 on 2026-06-26 00:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0007_add_categoria_to_municipalidad_delegado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="revisiondelegado",
            name="unique_liquidacion_delegado",
        ),
        migrations.RemoveField(
            model_name="revisiondelegado",
            name="delegado",
        ),
        migrations.RemoveField(
            model_name="revisiondelegado",
            name="liquidacion",
        ),
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="delegados",
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Periodo"
                    ),
                ),
                (
                    "dictamen_revision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("NO_CONFORME", "No conforme"),
                            ("PENDIENTE", "Pendiente"),
                            ("AP_OB", "AP.OB."),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Dictamen de Revision",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Presentacion"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Revision"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Delegado de Liquidacion",
                "verbose_name_plural": "historical Delegados de liquidaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Periodo"
                    ),
                ),
                (
                    "dictamen_revision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("NO_CONFORME", "No conforme"),
                            ("PENDIENTE", "Pendiente"),
                            ("AP_OB", "AP.OB."),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Dictamen de Revision",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Presentacion"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Revision"
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidacion_delegados",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_delegados",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delegado de Liquidacion",
                "verbose_name_plural": "Delegados de liquidaciones",
                "ordering": ["liquidacion", "delegado"],
            },
        ),
        migrations.DeleteModel(
            name="HistoricalRevisionDelegado",
        ),
        migrations.DeleteModel(
            name="RevisionDelegado",
        ),
        migrations.AddConstraint(
            model_name="liquidaciondelegado",
            constraint=models.UniqueConstraint(
                fields=("liquidacion", "delegado"), name="unique_liquidacion_delegado"
            ),
        ),
    ]
