# Generated by Django 5.2.12 on 2026-08-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0008_move_liquidacioninspector_fk_a_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="igv",
        ),
        migrations.RemoveField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="total",
        ),
        migrations.RemoveField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="uit",
        ),
        migrations.RemoveField(
            model_name="liquidacionporcentajeobradetalle",
            name="igv",
        ),
        migrations.RemoveField(
            model_name="liquidacionporcentajeobradetalle",
            name="total",
        ),
        migrations.RemoveField(
            model_name="liquidacionporcentajeobradetalle",
            name="uit",
        ),
        migrations.AlterField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto subtotal parcial de esta especialidad (antes de IGV). El IGV y el total se calculan a nivel global en LiquidacionGeneral.",
                max_digits=10,
                verbose_name="Subtotal Parcial",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionporcentajeobradetalle",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto subtotal parcial de esta especialidad (antes de IGV). El IGV y el total se calculan a nivel global en LiquidacionGeneral.",
                max_digits=10,
                verbose_name="Subtotal Parcial",
            ),
        ),
    ]
