# Generated by Django 5.2.11 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0008_remove_revisiondelegado_delegado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="expediente",
            field=models.CharField(
                blank=True,
                help_text="Número de expediente associated with the liquidacion.",
                max_length=100,
                null=True,
                verbose_name="Expediente",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="expediente",
            field=models.CharField(
                blank=True,
                help_text="Número de expediente associated with the liquidacion.",
                max_length=100,
                null=True,
                verbose_name="Expediente",
            ),
        ),
    ]
