# Generated by Django 5.2.11 on 2026-08-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0008_alter_historicalliquidacionporcentajeobra_derecho_minimo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifaporcategoriavisitas",
            name="tarifa_base",
            field=models.ForeignKey(
                help_text="Tarifa base asociada a esta tarifa por categoría de visitas.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_visitas",
                to="liquidaciones.tarifaliquidacionbase",
                verbose_name="Tarifa Base",
            ),
        ),
    ]
