# Generated by Django 5.2.11 on 2026-06-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0009_add_expediente_to_liquidaciongeneral"),
    ]

    operations = [
        # Remove valor_proyecto and valor_base_calculo from LiquidacionGeneral
        migrations.RemoveField(
            model_name="historicalliquidaciongeneral",
            name="valor_proyecto",
        ),
        migrations.RemoveField(
            model_name="historicalliquidaciongeneral",
            name="valor_base_calculo",
        ),
        migrations.RemoveField(
            model_name="liquidaciongeneral",
            name="valor_proyecto",
        ),
        migrations.RemoveField(
            model_name="liquidaciongeneral",
            name="valor_base_calculo",
        ),
        # Add valor_proyecto and valor_base_calculo to LiquidacionEdificaciones
        migrations.AddField(
            model_name="historicalliquidacionedificaciones",
            name="valor_base_calculo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor base sobre el cual se calculan los derechos. Si está vacío, se usa valor_proyecto.",
                max_digits=12,
                null=True,
                verbose_name="Valor Base de Cálculo",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionedificaciones",
            name="valor_proyecto",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor de Obra",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="valor_base_calculo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor base sobre el cual se calculan los derechos. Si está vacío, se usa valor_proyecto.",
                max_digits=12,
                null=True,
                verbose_name="Valor Base de Cálculo",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionedificaciones",
            name="valor_proyecto",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor de Obra",
            ),
        ),
    ]
