# Generated by Django 5.2.12 on 2026-08-21 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0009_remove_historicalliquidacionporcentajeobradetalle_igv_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
    ]