# Generated by Django 5.2.11 on 2026-08-11 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0009_change_visitas_onetoone_to_foreignkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Liquidación",
                "verbose_name_plural": "Tipos de Liquidación",
            },
        ),
    ]
