# Generated by Django 5.2.11 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0010_create_tipo_liquidacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones",
                to="liquidaciones.tipoliquidacion",
            ),
        ),
    ]
