# Generated by Django 5.2.11 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0010_move_valor_fields_to_edificaciones"),
    ]

    operations = [
        # Make valor_base_calculo NOT NULL (model already updated; this fixes DB)
        migrations.AlterField(
            model_name="historicalliquidacionedificaciones",
            name="valor_base_calculo",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor Base de Cálculo",
                help_text="Valor base sobre el cual se calculan los derechos.",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionedificaciones",
            name="valor_base_calculo",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Valor Base de Cálculo",
                help_text="Valor base sobre el cual se calculan los derechos.",
            ),
        ),
    ]
