# Generated by Django 5.2.11 on 2026-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0010_alter_historicalliquidaciongeneral_fecha_registro_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
    ]
