# Generated by Django 5.2.12 on 2026-08-24 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0011_create_rh_inspector_mensual"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidaciondelegado",
            name="numero_rh",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Orden/RH"
            ),
        ),
        migrations.AddField(
            model_name="liquidaciondelegado",
            name="numero_rh",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de Orden/RH"
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="fecha_registro",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora en que se registró la liquidación en el sistema.",
                verbose_name="Fecha de Registro",
            ),
        ),
    ]
