# Generated by Django 5.2.12 on 2026-06-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0011_require_valor_base_calculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegado",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("INACTIVO", "Inactivo"),
                    ("SUSPENDIDO", "Suspendido"),
                ],
                default="ACTIVO",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelegado",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVO", "Activo"),
                    ("INACTIVO", "Inactivo"),
                    ("SUSPENDIDO", "Suspendido"),
                ],
                default="ACTIVO",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionedificaciones",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmunicipalidaddelegado",
            name="tipo",
            field=models.CharField(
                choices=[("TITULAR", "Titular"), ("ALTERNO", "Alterno")],
                default="TITULAR",
                max_length=20,
                verbose_name="Tipo de Delegado",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionedificaciones",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AlterField(
            model_name="municipalidaddelegado",
            name="tipo",
            field=models.CharField(
                choices=[("TITULAR", "Titular"), ("ALTERNO", "Alterno")],
                default="TITULAR",
                max_length=20,
                verbose_name="Tipo de Delegado",
            ),
        ),
    ]
