# Generated by Django 5.2.11 on 2026-08-11 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0012_backfill_tipo_liquidacion_fk_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion_fk",
        ),
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Tipo de liquidación/formulario.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                help_text="Tipo de liquidación/formulario.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
    ]
