# Generated by Django 5.2.12 on 2026-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0012_historicalliquidaciondelegado_numero_rh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproyecto",
            name="denominacion",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Denominación del Proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="denominacion",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Denominación del Proyecto",
            ),
        ),
    ]
