# Generated by Django 5.2.12 on 2026-06-26 18:18

from django.db import migrations


def migrate_status_uppercase(apps, schema_editor):
    Delegado = apps.get_model("liquidaciones", "Delegado")
    HistoricalDelegado = apps.get_model("liquidaciones", "HistoricalDelegado")
    MunicipalidadDelegado = apps.get_model("liquidaciones", "MunicipalidadDelegado")
    HistoricalMunicipalidadDelegado = apps.get_model("liquidaciones", "HistoricalMunicipalidadDelegado")

    # Status mapping: lowercase → uppercase
    for old, new in [("activo", "ACTIVO"), ("inactivo", "INACTIVO"), ("suspendido", "SUSPENDIDO")]:
        Delegado.objects.filter(status=old).update(status=new)
        HistoricalDelegado.objects.filter(status=old).update(status=new)

    # Tipo mapping: lowercase → uppercase
    for old, new in [("titular", "TITULAR"), ("alterno", "ALTERNO")]:
        MunicipalidadDelegado.objects.filter(tipo=old).update(tipo=new)
        HistoricalMunicipalidadDelegado.objects.filter(tipo=old).update(tipo=new)


def reverse_migrate_status_lowercase(apps, schema_editor):
    Delegado = apps.get_model("liquidaciones", "Delegado")
    HistoricalDelegado = apps.get_model("liquidaciones", "HistoricalDelegado")
    MunicipalidadDelegado = apps.get_model("liquidaciones", "MunicipalidadDelegado")
    HistoricalMunicipalidadDelegado = apps.get_model("liquidaciones", "HistoricalMunicipalidadDelegado")

    for old, new in [("ACTIVO", "activo"), ("INACTIVO", "inactivo"), ("SUSPENDIDO", "suspendido")]:
        Delegado.objects.filter(status=old).update(status=new)
        HistoricalDelegado.objects.filter(status=old).update(status=new)

    for old, new in [("TITULAR", "titular"), ("ALTERNO", "alterno")]:
        MunicipalidadDelegado.objects.filter(tipo=old).update(tipo=new)
        HistoricalMunicipalidadDelegado.objects.filter(tipo=old).update(tipo=new)


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0012_update_delegado_status_uppercase"),
    ]

    operations = [
        migrations.RunPython(migrate_status_uppercase, reverse_migrate_status_lowercase),
    ]

