# Generated by Django 5.2.11 on 2026-08-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0013_tipo_liquidacion_char_to_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinspector",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionespecialidaddisponibles",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Tipo de liquidación/formulario.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="inspector",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspectores",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioncodigo",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                help_text="Tipo de liquidación/formulario.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="codigos",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionespecialidaddisponibles",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                help_text="Tipo de liquidación/formulario.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="especialidades_disponibles",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="tarifaliquidacionbase",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                help_text="Tipo de liquidación/formulario.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tarifas_base",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
    ]
