# Generated by Django 5.2.12 on 2026-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0013_make_denominacion_nullable"),
        ("usuarios", "0002_remove_codigo_especialidad_revision"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="liquidaciondelegado",
            name="unique_liquidacion_delegado",
        ),
        migrations.AddConstraint(
            model_name="liquidaciondelegado",
            constraint=models.UniqueConstraint(
                fields=("liquidacion", "delegado", "especialidad_revision"),
                name="unique_liquidacion_delegado_especialidad",
            ),
        ),
    ]
