# Generated by Django 5.2.11 on 2026-07-01 13:00

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0013_data_migrate_delegado_status_uppercase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TarifaPorcentajeObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "porcentaje_liquidacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje aplicado para el cálculo del derecho (ej: 0.0015 para 0.15%).",
                        max_digits=7,
                        verbose_name="Porcentaje de Liquidación",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto mínimo absoluto del derecho en soles.",
                        max_digits=10,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Monto máximo absoluto del derecho en soles (nulo = sin tope).",
                        max_digits=10,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                (
                    "porcentaje_minimo_uit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Mínimo como porcentaje de la UIT (protección para montos bajos).",
                        max_digits=5,
                        verbose_name="Porcentaje Mínimo UIT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa Porcentual de Obra",
                "verbose_name_plural": "Tarifas Porcentuales de Obra",
            },
        ),
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="proyectistas",
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="numero_revision",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número secuencial de revisión (1 = primera revisión).",
                verbose_name="Número de Revisión",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                help_text="Tipo de trámite/acción para esta liquidación (ej. obra_nueva, remodeling, etc.).",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="numero_revision",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número secuencial de revisión (1 = primera revisión).",
                verbose_name="Número de Revisión",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                help_text="Tipo de trámite/acción para esta liquidación (ej. obra_nueva, remodeling, etc.).",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.CreateModel(
            name="EspecialidadesLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificación"),
                            ("HABILITACION_URBANA", "Habilitación Urbana"),
                            ("MECANICA_SUELOS", "Mecánica de Suelos"),
                            ("IMPACTO_VIAL", "Impacto Vial"),
                            ("TALUDES", "Taludes"),
                            ("INSPECCION_OBRA", "Inspección de Obra"),
                        ],
                        default="EDIFICACION",
                        help_text="Tipo de formulario: edificacion, habilitacion_urbana, etc.",
                        max_length=30,
                        verbose_name="Tipo de Liquidación",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "especialidades",
                    models.ManyToManyField(
                        help_text="Especialidades habilitadas para este tipo de formulario.",
                        related_name="especialidades_liquidacion_grupo",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialidades de Liquidación",
                "verbose_name_plural": "Grupos de Especialidades de Liquidación",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEspecialidadesLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificación"),
                            ("HABILITACION_URBANA", "Habilitación Urbana"),
                            ("MECANICA_SUELOS", "Mecánica de Suelos"),
                            ("IMPACTO_VIAL", "Impacto Vial"),
                            ("TALUDES", "Taludes"),
                            ("INSPECCION_OBRA", "Inspección de Obra"),
                        ],
                        default="EDIFICACION",
                        help_text="Tipo de formulario: edificacion, habilitacion_urbana, etc.",
                        max_length=30,
                        verbose_name="Tipo de Liquidación",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Especialidades de Liquidación",
                "verbose_name_plural": "historical Grupos de Especialidades de Liquidación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTarifaPorcentajeObra",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "porcentaje_liquidacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje aplicado para el cálculo del derecho (ej: 0.0015 para 0.15%).",
                        max_digits=7,
                        verbose_name="Porcentaje de Liquidación",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto mínimo absoluto del derecho en soles.",
                        max_digits=10,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Monto máximo absoluto del derecho en soles (nulo = sin tope).",
                        max_digits=10,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                (
                    "porcentaje_minimo_uit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Mínimo como porcentaje de la UIT (protección para montos bajos).",
                        max_digits=5,
                        verbose_name="Porcentaje Mínimo UIT",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarifa Porcentual de Obra",
                "verbose_name_plural": "historical Tarifas Porcentuales de Obra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TarifaLiquidacionBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificación"),
                            ("HABILITACION_URBANA", "Habilitación Urbana"),
                            ("MECANICA_SUELOS", "Mecánica de Suelos"),
                            ("IMPACTO_VIAL", "Impacto Vial"),
                            ("TALUDES", "Taludes"),
                            ("INSPECCION_OBRA", "Inspección de Obra"),
                        ],
                        default="EDIFICACION",
                        help_text="Tipo de formulario/liquidación al que aplica esta tarifa.",
                        max_length=30,
                        verbose_name="Tipo de Liquidación",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "especialidades",
                    models.ManyToManyField(
                        help_text="Especialidades a las que aplica esta tarifa base.",
                        related_name="tarifas_liquidacion_base",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidades",
                    ),
                ),
                (
                    "tarifa_porcentaje",
                    models.ForeignKey(
                        help_text="Tarifa porcentual asociada a esta tarifa base.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tarifas_base",
                        to="liquidaciones.tarifaporcentajeobra",
                        verbose_name="Tarifa Porcentual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa Base de Liquidación",
                "verbose_name_plural": "Tarifas Base de Liquidación",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="LiquidacionPorcentajeObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "valor_proyecto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total del proyecto de edificación.",
                        max_digits=12,
                        verbose_name="Valor del Proyecto",
                    ),
                ),
                (
                    "valor_base_calculo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor sobre el cual se aplica el porcentaje (base imponible).",
                        max_digits=12,
                        verbose_name="Valor Base de Cálculo",
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_porcentaje_obra",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        help_text="Tarifa porcentual que se usó en este cálculo.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones_porcentaje",
                        to="liquidaciones.tarifaporcentajeobra",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación Porcentual de Obra",
                "verbose_name_plural": "Liquidaciones Porcentuales de Obra",
            },
        ),
        migrations.CreateModel(
            name="HistoricalTarifaLiquidacionBase",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificación"),
                            ("HABILITACION_URBANA", "Habilitación Urbana"),
                            ("MECANICA_SUELOS", "Mecánica de Suelos"),
                            ("IMPACTO_VIAL", "Impacto Vial"),
                            ("TALUDES", "Taludes"),
                            ("INSPECCION_OBRA", "Inspección de Obra"),
                        ],
                        default="EDIFICACION",
                        help_text="Tipo de formulario/liquidación al que aplica esta tarifa.",
                        max_length=30,
                        verbose_name="Tipo de Liquidación",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_porcentaje",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa porcentual asociada a esta tarifa base.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaporcentajeobra",
                        verbose_name="Tarifa Porcentual",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarifa Base de Liquidación",
                "verbose_name_plural": "historical Tarifas Base de Liquidación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionPorcentajeObra",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "valor_proyecto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total del proyecto de edificación.",
                        max_digits=12,
                        verbose_name="Valor del Proyecto",
                    ),
                ),
                (
                    "valor_base_calculo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor sobre el cual se aplica el porcentaje (base imponible).",
                        max_digits=12,
                        verbose_name="Valor Base de Cálculo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa porcentual que se usó en este cálculo.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaporcentajeobra",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación Porcentual de Obra",
                "verbose_name_plural": "historical Liquidaciones Porcentuales de Obra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionProyectista",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_proyectistas",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "proyectista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones_proyectista",
                        to="liquidaciones.proyectista",
                        verbose_name="Proyectista",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyectista de Liquidación",
                "verbose_name_plural": "Proyectistas de Liquidaciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liquidacion_general", "proyectista"),
                        name="unique_liquidacion_proyectista",
                    )
                ],
            },
        ),
    ]
