# Generated by Django 5.2.12 on 2026-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0014_fix_liquidacion_delegado_unique_especialidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="denominacion_de_proyecto_liquidacion",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Denominación de Proyecto de Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="descripcion_legacy",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción Legacy"
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="denominacion_de_proyecto_liquidacion",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Denominación de Proyecto de Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="descripcion_legacy",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descripción Legacy"
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionedificacion",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionhabilitacionurbana",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionimpactovial",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacioninspeccionobra",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionmecanicasuelos",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidaciontaludes",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionedificacion",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionhabilitacionurbana",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionimpactovial",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioninspeccionobra",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionmecanicasuelos",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciontaludes",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
    ]
