# Generated by Django 5.2.11 on 2026-07-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0014_tarifaporcentajeobra_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalliquidacionedificaciones",
            name="numero_revision",
        ),
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="numero_revision",
        ),
    ]
