# Generated by Django 5.2.11 on 2026-08-11 15:12

from django.db import migrations


def seed_tipos(apps, schema_editor):
    TipoLiquidacion = apps.get_model('liquidaciones', 'TipoLiquidacion')
    tipos = [
        ("EDIFICACION", "Edificaciones"),
        ("HABILITACION_URBANA", "Habilitación Urbana"),
        ("MECANICA_SUELOS", "Mecánica de Suelos"),
        ("IMPACTO_VIAL", "Impacto Vial"),
        ("TALUDES", "Taludes"),
        ("INSPECCION_OBRA", "Inspección de Obra"),
    ]
    for codigo, nombre in tipos:
        TipoLiquidacion.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre})


def reverse_tipos(apps, schema_editor):
    TipoLiquidacion = apps.get_model('liquidaciones', 'TipoLiquidacion')
    TipoLiquidacion.objects.filter(codigo__in=[
        "EDIFICACION", "HABILITACION_URBANA", "MECANICA_SUELOS",
        "IMPACTO_VIAL", "TALUDES", "INSPECCION_OBRA"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0014_tipo_liquidacion_fk_remaining_models"),
    ]

    operations = [
        migrations.RunPython(seed_tipos, reverse_tipos),
    ]
