# Generated by Django 5.2.11 on 2026-08-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_initial"),
        ("liquidaciones", "0015_seed_tipos_liquidacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="contacto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Contacto asociado a la liquidación.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.contacto",
                verbose_name="Contacto",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="contacto",
            field=models.ForeignKey(
                blank=True,
                help_text="Contacto asociado a la liquidación.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones_contacto",
                to="entidades.contacto",
                verbose_name="Contacto",
            ),
        ),
    ]
