# Generated by Django 5.2.11 on 2026-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0015_historicalliquidaciongeneral_denominacion_de_proyecto_liquidacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproyecto",
            name="entidad_tipo_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.tipo_documento al momento de crear el proyecto.",
                max_length=20,
                null=True,
                verbose_name="Tipo de Documento de Entidad (snapshot)",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="entidad_tipo_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.tipo_documento al momento de crear el proyecto.",
                max_length=20,
                null=True,
                verbose_name="Tipo de Documento de Entidad (snapshot)",
            ),
        ),
    ]
