# Generated by Django 5.2.11 on 2026-07-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0015_clean_numero_revision_duplicado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="revisiones",
        ),
    ]
