# Generated by Django 5.2.11 on 2026-07-01 14:41

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0016_remove_revisiones_m2m_and_numero_revision_duplicado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLiquidacionEdificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de edificaciones (ej. E-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tipo_tramite",
                    models.CharField(
                        choices=[
                            ("OBRA_NUEVA", "Obra Nueva"),
                            ("DEMOLICION", "Demolición"),
                            ("AMPLIACION", "Ampliación"),
                            ("REMODELACION", "Remodelación"),
                            ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                            ("REINTEGRO", "Reintegro"),
                            (
                                "PROYECTO_CON_PLANTAS_TIPICAS",
                                "Proyecto con Plantas Típicas",
                            ),
                        ],
                        default="OBRA_NUEVA",
                        max_length=30,
                        verbose_name="Tipo de Trámite",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Edificación",
                "verbose_name_plural": "historical Liquidaciones de Edificaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionEdificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de edificaciones (ej. E-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tipo_tramite",
                    models.CharField(
                        choices=[
                            ("OBRA_NUEVA", "Obra Nueva"),
                            ("DEMOLICION", "Demolición"),
                            ("AMPLIACION", "Ampliación"),
                            ("REMODELACION", "Remodelación"),
                            ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                            ("REINTEGRO", "Reintegro"),
                            (
                                "PROYECTO_CON_PLANTAS_TIPICAS",
                                "Proyecto con Plantas Típicas",
                            ),
                        ],
                        default="OBRA_NUEVA",
                        max_length=30,
                        verbose_name="Tipo de Trámite",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edificaciones",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Edificación",
                "verbose_name_plural": "Liquidaciones de Edificaciones",
            },
        ),
        migrations.RemoveField(
            model_name="edificacionesespecialidades",
            name="especialidades",
        ),
        migrations.RemoveField(
            model_name="edificacionesrevision",
            name="especialidades",
        ),
        migrations.RemoveField(
            model_name="edificacionesrevision",
            name="tarifa",
        ),
        migrations.RemoveField(
            model_name="historicaledificacionesespecialidades",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaledificacionestarifa",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalliquidacionedificaciones",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalliquidacionedificaciones",
            name="liquidacion",
        ),
        migrations.RemoveField(
            model_name="liquidacionedificaciones",
            name="liquidacion",
        ),
        migrations.DeleteModel(
            name="LiquidacionEdificacionesProxy",
        ),
        migrations.CreateModel(
            name="LiquidacionEdificacionProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación Edificación",
                "verbose_name_plural": "Liquidaciones Edificaciones",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.DeleteModel(
            name="EdificacionesEspecialidades",
        ),
        migrations.DeleteModel(
            name="EdificacionesRevision",
        ),
        migrations.DeleteModel(
            name="EdificacionesTarifa",
        ),
        migrations.DeleteModel(
            name="HistoricalEdificacionesEspecialidades",
        ),
        migrations.DeleteModel(
            name="HistoricalEdificacionesTarifa",
        ),
        migrations.DeleteModel(
            name="HistoricalLiquidacionEdificaciones",
        ),
        migrations.DeleteModel(
            name="LiquidacionEdificaciones",
        ),
    ]
