# Generated by Django 5.2.11 on 2026-08-28

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0016_alter_historicalproyecto_entidad_tipo_documento_and_more"),
    ]

    operations = [
        # ── LiquidacionDelegado ────────────────────────────────────────────────
        migrations.AlterField(
            model_name="liquidaciondelegado",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Periodo (Año)",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciondelegado",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mes (1-12)",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidaciondelegado",
            constraint=models.CheckConstraint(
                check=models.Q(mes__isnull=True) | models.Q(mes__gte=1, mes__lte=12),
                name="liquidacion_delegado_mes_valid",
            ),
        ),
        # ── HistoricalLiquidacionDelegado ─────────────────────────────────────
        migrations.AlterField(
            model_name="historicalliquidaciondelegado",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Periodo (Año)",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidaciondelegado",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mes (1-12)",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalliquidaciondelegado",
            constraint=models.CheckConstraint(
                check=models.Q(mes__isnull=True) | models.Q(mes__gte=1, mes__lte=12),
                name="historical_liquidacion_delegado_mes_valid",
            ),
        ),
        # ── LiquidacionInspector ───────────────────────────────────────────────
        migrations.AlterField(
            model_name="liquidacioninspector",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Periodo (Año)",
            ),
        ),
        migrations.AddField(
            model_name="liquidacioninspector",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mes (1-12)",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidacioninspector",
            constraint=models.CheckConstraint(
                check=models.Q(mes__isnull=True) | models.Q(mes__gte=1, mes__lte=12),
                name="liquidacion_inspector_mes_valid",
            ),
        ),
        # ── HistoricalLiquidacionInspector ────────────────────────────────────
        migrations.AlterField(
            model_name="historicalliquidacioninspector",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ],
                verbose_name="Periodo (Año)",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacioninspector",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mes (1-12)",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalliquidacioninspector",
            constraint=models.CheckConstraint(
                check=models.Q(mes__isnull=True) | models.Q(mes__gte=1, mes__lte=12),
                name="historical_liquidacion_inspector_mes_valid",
            ),
        ),
    ]
