# Generated by Django 5.2.11 on 2026-08-12 16:15

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0016_add_contacto_fk_to_liquidaciongeneral"),
        ("usuarios", "0002_add_fecha_busqueda_to_ingeniero_habilitacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInspectorTipoLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=1, verbose_name="Numero de Registro"),
                ),
                (
                    "numero_registro",
                    models.CharField(max_length=50, verbose_name="Numero de Registro"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Correo Electronico",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inspector",
                "verbose_name_plural": "historical Inspectores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InspectorTipoLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=1, verbose_name="Numero de Registro"),
                ),
                (
                    "numero_registro",
                    models.CharField(max_length=50, verbose_name="Numero de Registro"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Correo Electronico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector",
                "verbose_name_plural": "Inspectores",
                "ordering": [
                    "inspector__perfil_ingeniero__apellido_paterno",
                    "inspector__perfil_ingeniero__apellido_materno",
                ],
            },
        ),
        migrations.RemoveField(
            model_name="historicalinspector",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalinspector",
            name="perfil_ingeniero",
        ),
        migrations.RemoveField(
            model_name="historicalinspector",
            name="tipo_liquidacion",
        ),
        migrations.AlterModelOptions(
            name="inspector",
            options={
                "ordering": [
                    "perfil_ingeniero__apellido_paterno",
                    "perfil_ingeniero__apellido_materno",
                    "perfil_ingeniero__nombres",
                ],
                "verbose_name": "Inspector",
                "verbose_name_plural": "Inspectores",
            },
        ),
        migrations.RemoveConstraint(
            model_name="inspector",
            name="unique_inspector_registro",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="email",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="numero_registro",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="telefono",
        ),
        migrations.RemoveField(
            model_name="inspector",
            name="tipo_liquidacion",
        ),
        migrations.AlterField(
            model_name="inspector",
            name="perfil_ingeniero",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspectores_liquidacion",
                to="usuarios.perfilingeniero",
                verbose_name="Perfil de Ingeniero",
            ),
        ),
        migrations.AddField(
            model_name="historicalinspectortipoliquidacion",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalinspectortipoliquidacion",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.inspector",
                verbose_name="Inspector",
            ),
        ),
        migrations.AddField(
            model_name="historicalinspectortipoliquidacion",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="inspectortipoliquidacion",
            name="inspector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_liquidacion",
                to="liquidaciones.inspector",
                verbose_name="Inspector",
            ),
        ),
        migrations.AddField(
            model_name="inspectortipoliquidacion",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspectores",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalInspector",
        ),
        migrations.AddConstraint(
            model_name="inspectortipoliquidacion",
            constraint=models.UniqueConstraint(
                fields=("inspector", "tipo_liquidacion", "numero_registro"),
                name="unique_inspector_registro",
            ),
        ),
    ]
