# Generated by Django 5.2.11 on 2026-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0017_liquidacion_delegado_inspector_periodo_mes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="historicalliquidaciondelegado",
            name="historical_liquidacion_delegado_mes_valid",
        ),
        migrations.RemoveConstraint(
            model_name="historicalliquidacioninspector",
            name="historical_liquidacion_inspector_mes_valid",
        ),
    ]
