# Generated by Django 5.2.11 on 2026-07-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0017_historicalliquidacionedificacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltarifaliquidacionbase",
            name="tarifa_porcentaje",
        ),
        migrations.RemoveField(
            model_name="tarifaliquidacionbase",
            name="tarifa_porcentaje",
        ),
        migrations.AddField(
            model_name="historicaltarifaporcentajeobra",
            name="tarifa_base",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Tarifa base asociada a esta tarifa porcentual.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tarifaliquidacionbase",
                verbose_name="Tarifa Base",
            ),
        ),
        migrations.AddField(
            model_name="tarifaporcentajeobra",
            name="tarifa_base",
            field=models.OneToOneField(
                blank=True,
                help_text="Tarifa base asociada a esta tarifa porcentual.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalle_porcentual",
                to="liquidaciones.tarifaliquidacionbase",
                verbose_name="Tarifa Base",
            ),
        ),
    ]
