# Generated by Django 5.2.11 on 2026-08-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0017_historicalinspectortipoliquidacion_and_more"),
        ("usuarios", "0003_especialidadrevision_especialidadingeniero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidacionespecialidaddisponibles",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltarifaporcentajeobra",
            name="especialidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Especialidad de revisión a la que aplica esta tarifa porcentual.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionespecialidaddisponibles",
            name="especialidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones_especialidad",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="especialidades_revisadas",
            field=models.ManyToManyField(
                help_text="Especialidades de revisión que han sido revisadas en esta liquidación.",
                related_name="liquidaciones_revisadas",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidades Revisadas",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionporcentajeobradetalle",
            name="especialidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_porcentaje_obra",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="tarifaporcentajeobra",
            name="especialidad",
            field=models.ForeignKey(
                help_text="Especialidad de revisión a la que aplica esta tarifa porcentual.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tarifas_porcentuales",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revisión",
            ),
        ),
    ]
