# Generated by Django 5.2.12 on 2026-08-13 06:44

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_initial"),
        (
            "liquidaciones",
            "0018_alter_historicalliquidacionespecialidaddisponibles_especialidad_and_more",
        ),
        ("usuarios", "0004_delete_especialidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inspectorperiodo",
            name="inspector",
        ),
        migrations.RemoveField(
            model_name="historicaldelegadomunicipalidad",
            name="categoria",
        ),
        migrations.AddField(
            model_name="delegado",
            name="especialidad_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delegados",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad",
            ),
        ),
        migrations.AddField(
            model_name="delegadomunicipalidad",
            name="liquidacion_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delegados_municipalidad",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="delegadomunicipalidad",
            unique_together={("delegado", "municipalidad", "liquidacion_revision")},
        ),
        migrations.AddField(
            model_name="historicaldelegado",
            name="especialidad_revision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad",
            ),
        ),
        migrations.AddField(
            model_name="historicaldelegadomunicipalidad",
            name="liquidacion_revision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AddField(
            model_name="inspector",
            name="especialidad_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspectores",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inspector",
            unique_together={("perfil_ingeniero", "especialidad_revision")},
        ),
        migrations.CreateModel(
            name="HistoricalInspectorAsignacionPeriodo",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector_tipo_liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.inspectortipoliquidacion",
                        verbose_name="Inspector - Tipo de Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical inspector asignacion periodo",
                "verbose_name_plural": "historical inspector asignacion periodos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="InspectorAsignacionPeriodo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "inspector_tipo_liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periodos",
                        to="liquidaciones.inspectortipoliquidacion",
                        verbose_name="Inspector - Tipo de Liquidación",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="HistoricalInspectorPeriodo",
        ),
        migrations.DeleteModel(
            name="InspectorPeriodo",
        ),
        migrations.RemoveField(
            model_name="delegadomunicipalidad",
            name="categoria",
        ),
    ]
