# Generated by Django 5.2.11 on 2026-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0018_remove_historicalliquidaciondelegado_historical_liquidacion_delegado_mes_valid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la liquidación fue migrada del sistema legacy.",
                verbose_name="Legacy",
            ),
        ),
        migrations.AddField(
            model_name="liquidaciongeneral",
            name="legacy",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la liquidación fue migrada del sistema legacy.",
                verbose_name="Legacy",
            ),
        ),
    ]
