# Generated by Django 5.2.11 on 2026-07-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0018_reverse_tarifa_relacion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LiquidacionSnapshot",
        ),
    ]
