# Generated by Django 5.2.11 on 2026-07-02 06:05

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0019_delete_liquidacionsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReglaTarifaEdificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_tramite",
                    models.CharField(
                        choices=[
                            ("OBRA_NUEVA", "Obra Nueva"),
                            ("DEMOLICION", "Demolición"),
                            ("AMPLIACION", "Ampliación"),
                            ("REMODELACION", "Remodelación"),
                            ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                            ("REINTEGRO", "Reintegro"),
                            (
                                "PROYECTO_CON_PLANTAS_TIPICAS",
                                "Proyecto con Plantas Típicas",
                            ),
                        ],
                        help_text="Tipo de trámite de edificación al que aplica esta regla.",
                        max_length=30,
                        verbose_name="Tipo de Trámite",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa base asociada a esta regla.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Regla de Tarifa de Edificación",
                "verbose_name_plural": "historical Reglas de Tarifas de Edificación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReglaTarifaEdificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_tramite",
                    models.CharField(
                        choices=[
                            ("OBRA_NUEVA", "Obra Nueva"),
                            ("DEMOLICION", "Demolición"),
                            ("AMPLIACION", "Ampliación"),
                            ("REMODELACION", "Remodelación"),
                            ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                            ("REINTEGRO", "Reintegro"),
                            (
                                "PROYECTO_CON_PLANTAS_TIPICAS",
                                "Proyecto con Plantas Típicas",
                            ),
                        ],
                        help_text="Tipo de trámite de edificación al que aplica esta regla.",
                        max_length=30,
                        verbose_name="Tipo de Trámite",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        help_text="Tarifa base asociada a esta regla.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_tarifa",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Tarifa de Edificación",
                "verbose_name_plural": "Reglas de Tarifas de Edificación",
                "ordering": ["tipo_tramite", "tramite_accion"],
                "indexes": [
                    models.Index(
                        fields=["tipo_tramite", "tramite_accion"],
                        name="idx_regla_tipo_tramite_accion",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo_tramite", "tramite_accion", "tarifa_base"),
                        name="unique_regla_tarifa_edificacion",
                    )
                ],
            },
        ),
    ]
