# Generated by Django 5.2.11 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0019_add_legacy_to_liquidacion_general",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("PENDIENTE", "Pendiente"), ("PAGADA", "Pagada")],
                default="PENDIENTE",
                max_length=20,
                null=True,
                verbose_name="Estado de la Revisión",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[("PENDIENTE", "Pendiente"), ("PAGADA", "Pagada")],
                default="PENDIENTE",
                max_length=20,
                null=True,
                verbose_name="Estado de la Revisión",
            ),
        ),
    ]
