# Generated by Django 5.2.11 on 2026-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0020_historicalreglatarifaedificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproyecto",
            name="entidad_numero_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.numero_documento al momento de crear el proyecto.",
                max_length=11,
                null=True,
                verbose_name="Número de Documento de Entidad (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="historicalproyecto",
            name="entidad_razon_social",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.razon_social al momento de crear el proyecto.",
                max_length=255,
                null=True,
                verbose_name="Razón Social / Nombre de Entidad (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="historicalproyecto",
            name="entidad_tipo_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.tipo_documento al momento de crear el proyecto.",
                max_length=3,
                null=True,
                verbose_name="Tipo de Documento de Entidad (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="entidad_numero_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.numero_documento al momento de crear el proyecto.",
                max_length=11,
                null=True,
                verbose_name="Número de Documento de Entidad (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="entidad_razon_social",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.razon_social al momento de crear el proyecto.",
                max_length=255,
                null=True,
                verbose_name="Razón Social / Nombre de Entidad (snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="entidad_tipo_documento",
            field=models.CharField(
                blank=True,
                help_text="Copia de entidad.tipo_documento al momento de crear el proyecto.",
                max_length=3,
                null=True,
                verbose_name="Tipo de Documento de Entidad (snapshot)",
            ),
        ),
    ]
