# Generated by Django 5.2.11 on 2026-08-31 02:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0020_alter_estado_liquidacion_general_default_and_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidacionComprobante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FACTURA", "Factura"),
                            ("BOLETA", "Boleta"),
                            ("NOTA_CREDITO", "Nota de Crédito"),
                            ("NOTA_DEBITO", "Nota de Débito"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Comprobante",
                    ),
                ),
                (
                    "serie",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Serie"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Emisión"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si este es el comprobante activo de la liquidación.",
                        verbose_name="¿Activo?",
                    ),
                ),
                (
                    "motivo_reemplazo",
                    models.CharField(
                        blank=True,
                        help_text="Motivo por el cual este comprobante reemplazó a uno anterior.",
                        max_length=500,
                        null=True,
                        verbose_name="Motivo de Reemplazo",
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comprobantes",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante de Liquidación",
                "verbose_name_plural": "Comprobantes de Liquidaciones",
                "ordering": ["liquidacion_general", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("liquidacion_general",),
                        name="unique_liquidacion_comprobante_activo",
                    )
                ],
            },
        ),
    ]
