# Generated by Django 5.2.11 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0021_liquidacioncomprobante"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liquidacioncomprobante",
            options={
                "ordering": ["liquidacion_general", "-created_at"],
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
            },
        ),
    ]
