# Generated by Django 5.2.11 on 2026-08-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0021_historicalliquidaciondelegado_especialidad_revision_and_more",
        ),
        ("usuarios", "0004_delete_especialidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidaciondelegado",
            name="especialidad_revision",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revision",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciondelegado",
            name="especialidad_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidacion_delegados",
                to="usuarios.especialidadrevision",
                verbose_name="Especialidad de Revision",
            ),
        ),
    ]
