# Generated by Django 5.2.11 on 2026-07-03 07:44

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0021_historicalproyecto_entidad_numero_documento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidacionedificacion",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                help_text="Tipo de trámite/acción para esta liquidación (ej. obra_nueva, remodeling, etc.).",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreglatarifaedificacion",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                help_text="Tipo de trámite de edificación al que aplica esta regla.",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionedificacion",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                default="OBRA_NUEVA",
                help_text="Tipo de trámite/acción para esta liquidación (ej. obra_nueva, remodeling, etc.).",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="reglatarifaedificacion",
            name="tipo_tramite",
            field=models.CharField(
                choices=[
                    ("OBRA_NUEVA", "Obra Nueva"),
                    ("DEMOLICION", "Demolición"),
                    ("AMPLIACION", "Ampliación"),
                    ("REMODELACION", "Remodelación"),
                    ("MODIFICACION_LICENCIA", "Modificación de Licencia"),
                    ("VARIACION_PROYECTO_APROBADO", "Variación Proyecto Aprobado"),
                    ("REINTEGRO", "Reintegro"),
                    ("PROYECTO_CON_PLANTAS_TIPICAS", "Proyecto con Plantas Típicas"),
                ],
                help_text="Tipo de trámite de edificación al que aplica esta regla.",
                max_length=30,
                verbose_name="Tipo de Trámite",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionHabilitacionUrbana",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de habilitación urbana (ej. HU-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Habilitación Urbana",
                "verbose_name_plural": "historical Liquidaciones de Habilitaciones Urbanas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionImpactoVial",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de impacto vial (ej. IV-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Impacto Vial",
                "verbose_name_plural": "historical Liquidaciones de Impacto Vial",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionInspeccionObra",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de inspección de obra (ej. IO-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Inspección de Obra",
                "verbose_name_plural": "historical Liquidaciones de Inspección de Obra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionMecanicaSuelos",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de mecánica de suelos (ej. MS-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Mecánica de Suelos",
                "verbose_name_plural": "historical Liquidaciones de Mecánica de Suelos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionTaludes",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identificador público de la liquidación de taludes (ej. TAL-2026-00001).",
                        max_length=50,
                        null=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación de Taludes",
                "verbose_name_plural": "historical Liquidaciones de Taludes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReglaTarifaInspeccionObra",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría de inspección de obra: A, B, C, etc.",
                        max_length=20,
                        verbose_name="Categoría de Inspección",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa base asociada a esta regla.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Regla de Tarifa de Inspección de Obra",
                "verbose_name_plural": "historical Reglas de Tarifas de Inspección de Obra",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReglaTarifaLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa base asociada a esta regla.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Regla de Tarifa de Liquidación",
                "verbose_name_plural": "historical Reglas de Tarifas de Liquidación",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTarifaPorCategoriaVisitas",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "costo_por_visita",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo por cada visita de inspección en soles.",
                        max_digits=10,
                        verbose_name="Costo por Visita",
                    ),
                ),
                (
                    "visitas_minimas",
                    models.PositiveIntegerField(
                        help_text="Número mínimo de visitas para el cálculo (se usa max(cantidad_visitas, visitas_minimas)).",
                        verbose_name="Visitas Mínimas",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa base asociada a esta tarifa por categoría de visitas.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarifa por Categoría de Visitas",
                "verbose_name_plural": "historical Tarifas por Categoría de Visitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTarifaPorMetroCuadrado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "costo_por_m2",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Costo por metro cuadrado en soles.",
                        max_digits=10,
                        verbose_name="Costo por M2",
                    ),
                ),
                (
                    "area_minima",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área mínima en metros cuadrados para el cálculo (se usa max(area_solicitada, area_minima)).",
                        max_digits=10,
                        verbose_name="Área Mínima",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto mínimo absoluto del derecho en soles.",
                        max_digits=12,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto máximo absoluto del derecho en soles (nulo = sin tope).",
                        max_digits=12,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa base asociada a esta tarifa por metro cuadrado.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tarifa por Metro Cuadrado",
                "verbose_name_plural": "historical Tarifas por Metro Cuadrado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionHabilitacionUrbana",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de habilitación urbana (ej. HU-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habilitacion_urbana",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Habilitación Urbana",
                "verbose_name_plural": "Liquidaciones de Habilitaciones Urbanas",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionImpactoVial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de impacto vial (ej. IV-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacto_vial",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Impacto Vial",
                "verbose_name_plural": "Liquidaciones de Impacto Vial",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionInspeccionObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de inspección de obra (ej. IO-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspeccion_obra",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Inspección de Obra",
                "verbose_name_plural": "Liquidaciones de Inspección de Obra",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionMecanicaSuelos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de mecánica de suelos (ej. MS-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mecanica_suelos",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Mecánica de Suelos",
                "verbose_name_plural": "Liquidaciones de Mecánica de Suelos",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionTaludes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador público de la liquidación de taludes (ej. TAL-2026-00001).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="ID Público",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        default="PRIMERA_REVISION",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "liquidacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taludes",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación de Taludes",
                "verbose_name_plural": "Liquidaciones de Taludes",
            },
        ),
        migrations.CreateModel(
            name="TarifaPorCategoriaVisitas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "costo_por_visita",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo por cada visita de inspección en soles.",
                        max_digits=10,
                        verbose_name="Costo por Visita",
                    ),
                ),
                (
                    "visitas_minimas",
                    models.PositiveIntegerField(
                        help_text="Número mínimo de visitas para el cálculo (se usa max(cantidad_visitas, visitas_minimas)).",
                        verbose_name="Visitas Mínimas",
                    ),
                ),
                (
                    "tarifa_base",
                    models.OneToOneField(
                        help_text="Tarifa base asociada a esta tarifa por categoría de visitas.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_visitas",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa por Categoría de Visitas",
                "verbose_name_plural": "Tarifas por Categoría de Visitas",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionPorCategoriaVisitas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "cantidad_visitas",
                    models.PositiveIntegerField(
                        help_text="Número de visitas de inspección realizadas o programadas.",
                        verbose_name="Cantidad de Visitas",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría de inspección: A, B, C, etc.",
                        max_length=20,
                        verbose_name="Categoría de Inspección",
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_visitas",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        help_text="Tarifa por categoría de visitas que se usó en este cálculo.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="liquidaciones_visitas",
                        to="liquidaciones.tarifaporcategoriavisitas",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación por Categoría de Visitas",
                "verbose_name_plural": "Liquidaciones por Categoría de Visitas",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionPorCategoriaVisitas",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "cantidad_visitas",
                    models.PositiveIntegerField(
                        help_text="Número de visitas de inspección realizadas o programadas.",
                        verbose_name="Cantidad de Visitas",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría de inspección: A, B, C, etc.",
                        max_length=20,
                        verbose_name="Categoría de Inspección",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa por categoría de visitas que se usó en este cálculo.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifaporcategoriavisitas",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación por Categoría de Visitas",
                "verbose_name_plural": "historical Liquidaciones por Categoría de Visitas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TarifaPorMetroCuadrado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "costo_por_m2",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Costo por metro cuadrado en soles.",
                        max_digits=10,
                        verbose_name="Costo por M2",
                    ),
                ),
                (
                    "area_minima",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área mínima en metros cuadrados para el cálculo (se usa max(area_solicitada, area_minima)).",
                        max_digits=10,
                        verbose_name="Área Mínima",
                    ),
                ),
                (
                    "derecho_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto mínimo absoluto del derecho en soles.",
                        max_digits=12,
                        verbose_name="Derecho Mínimo",
                    ),
                ),
                (
                    "derecho_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto máximo absoluto del derecho en soles (nulo = sin tope).",
                        max_digits=12,
                        null=True,
                        verbose_name="Derecho Máximo",
                    ),
                ),
                (
                    "tarifa_base",
                    models.OneToOneField(
                        help_text="Tarifa base asociada a esta tarifa por metro cuadrado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_m2",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa por Metro Cuadrado",
                "verbose_name_plural": "Tarifas por Metro Cuadrado",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionPorMetroCuadrado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "area_solicitada",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área total solicitada en metros cuadrados.",
                        max_digits=12,
                        verbose_name="Área Solicitada",
                    ),
                ),
                (
                    "area_base_calculo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área real aplicada tras evaluar area_minima (max(area_solicitada, area_minima)).",
                        max_digits=12,
                        verbose_name="Área Base de Cálculo",
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_m2",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        help_text="Tarifa por metro cuadrado que se usó en este cálculo.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="liquidaciones_m2",
                        to="liquidaciones.tarifapormetrocuadrado",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidación por Metro Cuadrado",
                "verbose_name_plural": "Liquidaciones por Metro Cuadrado",
            },
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionPorMetroCuadrado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "area_solicitada",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área total solicitada en metros cuadrados.",
                        max_digits=12,
                        verbose_name="Área Solicitada",
                    ),
                ),
                (
                    "area_base_calculo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Área real aplicada tras evaluar area_minima (max(area_solicitada, area_minima)).",
                        max_digits=12,
                        verbose_name="Área Base de Cálculo",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_general",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidación General",
                    ),
                ),
                (
                    "tarifa_aplicada",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Tarifa por metro cuadrado que se usó en este cálculo.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.tarifapormetrocuadrado",
                        verbose_name="Tarifa Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Liquidación por Metro Cuadrado",
                "verbose_name_plural": "historical Liquidaciones por Metro Cuadrado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReglaTarifaInspeccionObra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoría de inspección de obra: A, B, C, etc.",
                        max_length=20,
                        verbose_name="Categoría de Inspección",
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        help_text="Tarifa base asociada a esta regla.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_tarifa_inspeccion",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Tarifa de Inspección de Obra",
                "verbose_name_plural": "Reglas de Tarifas de Inspección de Obra",
                "ordering": ["categoria", "tramite_accion"],
                "indexes": [
                    models.Index(
                        fields=["categoria", "tramite_accion"],
                        name="idx_regla_insp_cat_accion",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("categoria", "tramite_accion", "tarifa_base"),
                        name="unique_regla_tarifa_inspeccion",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReglaTarifaLiquidacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tramite_accion",
                    models.CharField(
                        choices=[
                            ("PRIMERA_REVISION", "Primera Revisión"),
                            ("REVISION", "Revisión"),
                        ],
                        help_text="Acción de trámite: PRIMERA_REVISION o REVISION.",
                        max_length=20,
                        verbose_name="Acción de Trámite",
                    ),
                ),
                (
                    "tarifa_base",
                    models.ForeignKey(
                        help_text="Tarifa base asociada a esta regla.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_tarifa_liquidacion",
                        to="liquidaciones.tarifaliquidacionbase",
                        verbose_name="Tarifa Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Tarifa de Liquidación",
                "verbose_name_plural": "Reglas de Tarifas de Liquidación",
                "ordering": ["tramite_accion"],
                "indexes": [
                    models.Index(fields=["tramite_accion"], name="idx_regla_liq_accion")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tramite_accion", "tarifa_base"),
                        name="unique_regla_tarifa_liquidacion",
                    )
                ],
            },
        ),
    ]
