# Generated by Django 5.2.11 on 2026-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0022_alter_historicalliquidacionedificacion_tipo_tramite_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("EDIFICACION", "Edificación"),
                    ("HABILITACION_URBANA", "Habilitación Urbana"),
                    ("MECANICA_SUELOS", "Mecánica de Suelos"),
                    ("IMPACTO_VIAL", "Impacto Vial"),
                    ("TALUDES", "Taludes"),
                    ("INSPECCION_OBRA", "Inspección de Obra"),
                ],
                default="EDIFICACION",
                help_text="Tipo de liquidación/formulario: EDIFICACION, HABILITACION_URBANA, MECANICA_SUELOS, IMPACTO_VIAL, TALUDES, INSPECCION_OBRA.",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="tipo_liquidacion",
            field=models.CharField(
                choices=[
                    ("EDIFICACION", "Edificación"),
                    ("HABILITACION_URBANA", "Habilitación Urbana"),
                    ("MECANICA_SUELOS", "Mecánica de Suelos"),
                    ("IMPACTO_VIAL", "Impacto Vial"),
                    ("TALUDES", "Taludes"),
                    ("INSPECCION_OBRA", "Inspección de Obra"),
                ],
                default="EDIFICACION",
                help_text="Tipo de liquidación/formulario: EDIFICACION, HABILITACION_URBANA, MECANICA_SUELOS, IMPACTO_VIAL, TALUDES, INSPECCION_OBRA.",
                max_length=30,
                verbose_name="Tipo de Liquidación",
            ),
        ),
    ]
