# Generated by Django 5.2.11 on 2026-08-31 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0003_alter_entidad_tipo_documento_and_more"),
        ("finanzas", "0007_create_tasa_delegado"),
        ("liquidaciones", "0022_alter_liquidacioncomprobante_options"),
        ("usuarios", "0002_remove_codigo_especialidad_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="liquidaciongeneral",
            index=models.Index(
                fields=["proyecto", "tipo_liquidacion", "-numero_revision"],
                name="liquidacion_proyect_4dd303_idx",
            ),
        ),
    ]
