# Generated by Django 5.2.11 on 2026-07-03 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0023_fix_tipo_liquidacion_tipo_liquidacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionporcategoriavisitas",
            name="derecho",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monto del derecho calculado (= visitas_base_calculo * costo_por_visita).",
                max_digits=12,
                verbose_name="Derecho",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionporcategoriavisitas",
            name="visitas_base_calculo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de visitas usadas para el cálculo (max(cantidad_visitas, visitas_minimas)).",
                verbose_name="Visitas Base de Cálculo",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionpormetrocuadrado",
            name="derecho",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monto del derecho calculado con clamps de derecho_minimo y derecho_maximo aplicados.",
                max_digits=12,
                verbose_name="Derecho",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionporcategoriavisitas",
            name="derecho",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monto del derecho calculado (= visitas_base_calculo * costo_por_visita).",
                max_digits=12,
                verbose_name="Derecho",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionporcategoriavisitas",
            name="visitas_base_calculo",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad de visitas usadas para el cálculo (max(cantidad_visitas, visitas_minimas)).",
                verbose_name="Visitas Base de Cálculo",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionpormetrocuadrado",
            name="derecho",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monto del derecho calculado con clamps de derecho_minimo y derecho_maximo aplicados.",
                max_digits=12,
                verbose_name="Derecho",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionporcategoriavisitas",
            name="cantidad_visitas",
            field=models.PositiveIntegerField(
                help_text="Número de visitas de inspección solicitadas.",
                verbose_name="Cantidad de Visitas",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionporcategoriavisitas",
            name="cantidad_visitas",
            field=models.PositiveIntegerField(
                help_text="Número de visitas de inspección solicitadas.",
                verbose_name="Cantidad de Visitas",
            ),
        ),
    ]
