# Generated by Django 5.2.11 on 2026-09-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0023_add_liquidacion_general_compound_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalliquidacionedificacion",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionhabilitacionurbana",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionimpactovial",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacioninspeccionobra",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidacionmecanicasuelos",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="historicalliquidaciontaludes",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionedificacion",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionhabilitacionurbana",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionimpactovial",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioninspeccionobra",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidacionmecanicasuelos",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciontaludes",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Numero asignado automaticamente por el sistema.",
                null=True,
                verbose_name="Numero",
            ),
        ),
    ]
