# Generated by Django migration maker

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0024_alter_historicalliquidacionedificacion_numero_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liquidaciongeneral",
            old_name="denominacion_de_proyecto_liquidacion",
            new_name="denominacion_de_proyecto",
        ),
    ]
