# Generated by Django migration maker

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0025_rename_denominacion_de_proyecto_liquidacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="denominacion",
        ),
    ]
