# Generated by Django 5.2.11 on 2026-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0025_rename_area_minima_to_area_m2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltarifapormetrocuadrado",
            name="area_m2",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Área base en metros cuadrados para el cálculo (se usa max(area_solicitada, area_m2)).",
                max_digits=10,
                verbose_name="Área m²",
            ),
        ),
        migrations.AlterField(
            model_name="tarifapormetrocuadrado",
            name="area_m2",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Área base en metros cuadrados para el cálculo (se usa max(area_solicitada, area_m2)).",
                max_digits=10,
                verbose_name="Área m²",
            ),
        ),
    ]
