# Generated by Django 5.2.12 on 2026-07-26 22:09

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0026_alter_historicaltarifapormetrocuadrado_area_m2_and_more",
        ),
        ("usuarios", "0004_historicalperfilingeniero_condicion_cip_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificacion"),
                            ("HABILITACION_URBANA", "Habilitacion Urbana"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Liquidacion",
                    ),
                ),
                (
                    "categoria",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "numero_registro",
                    models.CharField(max_length=50, verbose_name="Numero de Registro"),
                ),
                ("vigencia", models.DateField(verbose_name="Vigencia")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inspector",
                "verbose_name_plural": "historical Inspectores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Inspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        choices=[
                            ("EDIFICACION", "Edificacion"),
                            ("HABILITACION_URBANA", "Habilitacion Urbana"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Liquidacion",
                    ),
                ),
                (
                    "categoria",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Categoria"
                    ),
                ),
                (
                    "numero_registro",
                    models.CharField(max_length=50, verbose_name="Numero de Registro"),
                ),
                ("vigencia", models.DateField(verbose_name="Vigencia")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        default="ACTIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspectores",
                        to="liquidaciones.especialidad",
                        verbose_name="Especialidad",
                    ),
                ),
                (
                    "perfil_ingeniero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspectores_liquidacion",
                        to="usuarios.perfilingeniero",
                        verbose_name="Perfil de Ingeniero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector",
                "verbose_name_plural": "Inspectores",
                "ordering": [
                    "perfil_ingeniero__apellido_paterno",
                    "perfil_ingeniero__apellido_materno",
                    "especialidad__nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLiquidacionInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Periodo"
                    ),
                ),
                (
                    "dictamen_revision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("NO_CONFORME", "No conforme"),
                            ("PENDIENTE", "Pendiente"),
                            ("AP_OB", "AP.OB."),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Dictamen de Revision",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Presentacion"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Revision"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidacion",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.inspector",
                        verbose_name="Inspector",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inspector de Liquidacion",
                "verbose_name_plural": "historical Inspectores de liquidaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LiquidacionInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Periodo"
                    ),
                ),
                (
                    "dictamen_revision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("NO_CONFORME", "No conforme"),
                            ("PENDIENTE", "Pendiente"),
                            ("AP_OB", "AP.OB."),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Dictamen de Revision",
                    ),
                ),
                (
                    "fecha_presentacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Presentacion"
                    ),
                ),
                (
                    "fecha_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Revision"
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidacion_inspectores",
                        to="liquidaciones.inspector",
                        verbose_name="Inspector",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidacion_inspectores",
                        to="liquidaciones.liquidaciongeneral",
                        verbose_name="Liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspector de Liquidacion",
                "verbose_name_plural": "Inspectores de liquidaciones",
                "ordering": ["liquidacion", "inspector"],
            },
        ),
        migrations.AddConstraint(
            model_name="inspector",
            constraint=models.UniqueConstraint(
                fields=(
                    "perfil_ingeniero",
                    "tipo_liquidacion",
                    "especialidad",
                    "numero_registro",
                ),
                name="unique_inspector_registro",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidacioninspector",
            constraint=models.UniqueConstraint(
                fields=("liquidacion", "inspector"), name="unique_liquidacion_inspector"
            ),
        ),
    ]
