# Generated by Django 5.2.11 on 2026-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0026_remove_proyecto_denominacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liquidacioncontacto",
            options={
                "ordering": ["-principal", "liquidacion__proyecto__nombre_propietario"],
                "verbose_name": "Liquidación - Contacto",
                "verbose_name_plural": "Liquidaciones - Contactos",
            },
        ),
        migrations.AlterModelOptions(
            name="proyecto",
            options={
                "ordering": ["nombre_propietario"],
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
        migrations.RemoveField(
            model_name="historicalliquidaciongeneral",
            name="denominacion_de_proyecto_liquidacion",
        ),
        migrations.RemoveField(
            model_name="historicalproyecto",
            name="denominacion",
        ),
        migrations.AddField(
            model_name="historicalliquidaciongeneral",
            name="denominacion_de_proyecto",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Denominación de Proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="liquidaciongeneral",
            name="denominacion_de_proyecto",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Denominación de Proyecto",
            ),
        ),
    ]
