# Generated by Django 5.2.11 on 2026-09-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0027_alter_liquidacioncontacto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidacionEdificacionProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Edificación",
                "verbose_name_plural": "Liquidaciones de Edificación",
                "ordering": ["-edificaciones__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionHabilitacionUrbanaProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Habilitación Urbana",
                "verbose_name_plural": "Liquidaciones de Habilitación Urbana",
                "ordering": ["-habilitacion_urbana__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionImpactoVialProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Impacto Vial",
                "verbose_name_plural": "Liquidaciones de Impacto Vial",
                "ordering": ["-impacto_vial__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionInspeccionObraProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Inspección de Obra",
                "verbose_name_plural": "Liquidaciones de Inspección de Obra",
                "ordering": ["-inspeccion_obra__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionMecanicaSuelosProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Mecánica de Suelos",
                "verbose_name_plural": "Liquidaciones de Mecánica de Suelos",
                "ordering": ["-mecanica_suelos__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
        migrations.CreateModel(
            name="LiquidacionTaludesProxy",
            fields=[],
            options={
                "verbose_name": "Liquidación de Taludes",
                "verbose_name_plural": "Liquidaciones de Taludes",
                "ordering": ["-taludes__numero"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("liquidaciones.liquidaciongeneral",),
        ),
    ]
