# Generated by Django 5.2.11 on 2026-09-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0028_liquidacionedificacionproxy_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="liquidacionedificacionproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Edificación",
                "verbose_name_plural": "Liquidaciones de Edificación",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidacionhabilitacionurbanaproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Habilitación Urbana",
                "verbose_name_plural": "Liquidaciones de Habilitación Urbana",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidacionimpactovialproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Impacto Vial",
                "verbose_name_plural": "Liquidaciones de Impacto Vial",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidacioninspeccionobraproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Inspección de Obra",
                "verbose_name_plural": "Liquidaciones de Inspección de Obra",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidacionmecanicasuelosproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Mecánica de Suelos",
                "verbose_name_plural": "Liquidaciones de Mecánica de Suelos",
            },
        ),
        migrations.AlterModelOptions(
            name="liquidaciontaludesproxy",
            options={
                "ordering": ["-fecha_registro"],
                "verbose_name": "Liquidación de Taludes",
                "verbose_name_plural": "Liquidaciones de Taludes",
            },
        ),
    ]
