# Generated by Django 5.2.11 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0029_alter_liquidacionedificacionproxy_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add FK to DelegadoOperacion on LiquidacionDelegado
        migrations.AddField(
            model_name="liquidaciondelegado",
            name="delegado_operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidacion_delegados",
                to="liquidaciones.delegadooperacion",
                verbose_name="Delegado Operatividad",
            ),
        ),
        # Add FK to DelegadoOperacion on HistoricalLiquidacionDelegado
        migrations.AddField(
            model_name="HistoricalLiquidacionDelegado",
            name="delegado_operacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.delegadooperacion",
                verbose_name="Delegado Operatividad",
            ),
        ),
    ]
