# Generated by Django 5.2.11 on 2026-09-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0031_rename_liquidacion_revision_to_tipo_liquidacion"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historicaldelegadooperacion",
            unique_together=set(),
        ),
    ]
