# Generated by Django 5.2.11 on 2026-09-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0032_alter_historicaldelegadooperacion_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacioninspector",
            name="inspector_operacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.inspectoroperacion",
                verbose_name="Inspector de Operación",
            ),
        ),
        migrations.AddField(
            model_name="liquidacioninspector",
            name="inspector_operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liquidaciones_inspector",
                to="liquidaciones.inspectoroperacion",
                verbose_name="Inspector de Operación",
            ),
        ),
    ]
