# Generated by Django 5.2.11 on 2026-09-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "liquidaciones",
            "0034_historicalinspector_historicalliquidacioncodigo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="ajuste_redondeo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ajuste por redondeo aplicado a esta especialidad.",
                max_digits=12,
                null=True,
                verbose_name="Ajuste de Redondeo",
            ),
        ),
        migrations.AddField(
            model_name="historicalliquidacionporcentajeobradetalle",
            name="importe_parcial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe parcial calculado para esta especialidad.",
                max_digits=12,
                null=True,
                verbose_name="Importe Parcial",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionporcentajeobradetalle",
            name="ajuste_redondeo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ajuste por redondeo aplicado a esta especialidad.",
                max_digits=12,
                null=True,
                verbose_name="Ajuste de Redondeo",
            ),
        ),
        migrations.AddField(
            model_name="liquidacionporcentajeobradetalle",
            name="importe_parcial",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe parcial calculado para esta especialidad.",
                max_digits=12,
                null=True,
                verbose_name="Importe Parcial",
            ),
        ),
    ]
