# Generated by Django 5.2.11 on 2026-10-05 09:04

import django.core.validators
import simple_history.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetalleHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto (del detalle porcentual)",
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fondo Común",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Neto Honorario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Honorario del Delegado",
                "verbose_name_plural": "Detalles de Honorarios del Delegado",
                "ordering": ["recibo_mensual", "liquidacion_delegado"],
            },
        ),
        migrations.CreateModel(
            name="DetalleHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_liquidadas",
                    models.IntegerField(verbose_name="Inspecciones Liquidadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspeccion",
                    ),
                ),
                (
                    "monto_contribuido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Contribuido",
                    ),
                ),
                (
                    "importe_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "inspecciones_pagadas_hasta_mes_anterior",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "saldo_restante",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tasa_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Honorario del Inspector",
                "verbose_name_plural": "Detalles de Honorarios del Inspector",
                "ordering": ["recibo_mensual", "liquidacion_por_categoria_visitas"],
            },
        ),
        migrations.CreateModel(
            name="EscalaDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Escala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Descuento del Inspector",
                "verbose_name_plural": "Escalas de Descuento del Inspector",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDetalleHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto (del detalle porcentual)",
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Sub Total",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Fondo Común",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Neto Honorario",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Honorario del Delegado",
                "verbose_name_plural": "historical Detalles de Honorarios del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDetalleHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_liquidadas",
                    models.IntegerField(verbose_name="Inspecciones Liquidadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspeccion",
                    ),
                ),
                (
                    "monto_contribuido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Contribuido",
                    ),
                ),
                (
                    "importe_bruto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "inspecciones_pagadas_hasta_mes_anterior",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "saldo_restante",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tasa_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Honorario del Inspector",
                "verbose_name_plural": "historical Detalles de Honorarios del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEscalaDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Escala",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Escala de Descuento del Inspector",
                "verbose_name_plural": "historical Escalas de Descuento del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIGV",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tasa de IGV como fracción decimal (ej. 0.18 para 18%)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Tasa IGV",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical IGV",
                "verbose_name_plural": "historical IGV",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRangoDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Mínimo"
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Máximo (null = sin tope)",
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.15 = 15%",
                        max_digits=5,
                        verbose_name="Porcentaje de Descuento",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rango de Descuento del Inspector",
                "verbose_name_plural": "historical Rangos de Descuento del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReciboHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Subtotal Liquidación",
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe Bruto"
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Renta CIP"
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Aporte CODEMU"
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Fondo Común"
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto Honorario"
                    ),
                ),
                (
                    "honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Honorario"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios del Delegado",
                "verbose_name_plural": "historical Recibos de Honorarios del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReciboHonorarioDelegadoMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año del Periodo"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes (suma de imp_bruto)",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Renta CIP (25%)"
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU (5%)",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común (10%)",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto Honorario"
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de RH"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios Mensual del Delegado",
                "verbose_name_plural": "historical Recibos de Honorarios Mensuales del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReciboHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.IntegerField(verbose_name="Inspecciones Programadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspección",
                    ),
                ),
                (
                    "inspecciones_mes",
                    models.IntegerField(verbose_name="Inspecciones del Mes"),
                ),
                (
                    "monto_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Bruto del Mes",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                (
                    "saldo_inspecciones",
                    models.IntegerField(verbose_name="Saldo de Inspecciones"),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sub Total"
                    ),
                ),
                (
                    "tasa_descuento_aplicada",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios del Inspector",
                "verbose_name_plural": "historical Recibos de Honorarios del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReciboHonorarioInspectorMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de RH"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año del Periodo"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
                (
                    "tasa_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios Mensual del Inspector",
                "verbose_name_plural": "historical Recibos de Honorarios Mensuales del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRegistroPagoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Año del Periodo",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes (1-12)",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Registro de Pago del Inspector",
                "verbose_name_plural": "historical Registros de Pago del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRHReparticionEstacional",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        help_text="Año de la repartición (e.g., 2026)",
                        verbose_name="Año del Periodo",
                    ),
                ),
                (
                    "total_fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Suma del fondo_comun de los DetalleHonorarioDelegado relacionados",
                        max_digits=12,
                        verbose_name="Total Fondo Común",
                    ),
                ),
                (
                    "numero_capitulos",
                    models.PositiveSmallIntegerField(
                        help_text="Cantidad de capítulos vinculados a la especialidad en este cálculo",
                        verbose_name="Número de Capítulos",
                    ),
                ),
                (
                    "numero_delegados",
                    models.PositiveSmallIntegerField(
                        help_text="Cantidad de delegados seleccionados",
                        verbose_name="Número de Delegados",
                    ),
                ),
                (
                    "monto_por_participacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto por cada delegado o capítulo (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto por Participación",
                    ),
                ),
                (
                    "residual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Diferencia no distribuible (total_fondo_comun - suma de partes)",
                        max_digits=12,
                        verbose_name="Residual",
                    ),
                ),
                (
                    "mes_desde",
                    models.PositiveSmallIntegerField(
                        help_text="Mes inicial del rango de la repartición",
                        verbose_name="Mes Desde (1-12)",
                    ),
                ),
                (
                    "mes_hasta",
                    models.PositiveSmallIntegerField(
                        help_text="Mes final del rango de la repartición",
                        verbose_name="Mes Hasta (1-12)",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Repartición Estacional",
                "verbose_name_plural": "historical Reparticiones Estacionales",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRHReparticionEstacionalCapitulo",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto recibido por este capítulo (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto Asignado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Capítulo en Repartición Estacional",
                "verbose_name_plural": "historical Detalles de Capítulos en Reparticiones Estacionales",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRHReparticionEstacionalDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto recibido por este delegado (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto Asignado",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Delegado en Repartición Estacional",
                "verbose_name_plural": "historical Detalles de Delegados en Reparticiones Estacionales",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTasaDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Tasa",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.25 = 25%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.05 = 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.10 = 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Fondo Común",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tasa de Delegado",
                "verbose_name_plural": "historical Tasas de Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUIT",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "valor",
                    models.IntegerField(
                        help_text="Valor de la UIT en soles",
                        verbose_name="Valor UIT (S/)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical UIT",
                "verbose_name_plural": "historical UIT",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IGV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tasa de IGV como fracción decimal (ej. 0.18 para 18%)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Tasa IGV",
                    ),
                ),
            ],
            options={
                "verbose_name": "IGV",
                "verbose_name_plural": "IGV",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="RangoDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Mínimo"
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Máximo (null = sin tope)",
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Ej: 0.15 = 15%",
                        max_digits=5,
                        verbose_name="Porcentaje de Descuento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango de Descuento del Inspector",
                "verbose_name_plural": "Rangos de Descuento del Inspector",
                "ordering": ["escala", "monto_minimo"],
            },
        ),
        migrations.CreateModel(
            name="ReciboHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Subtotal Liquidación",
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe Bruto"
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Renta CIP"
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Aporte CODEMU"
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Fondo Común"
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto Honorario"
                    ),
                ),
                (
                    "honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Honorario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios del Delegado",
                "verbose_name_plural": "Recibos de Honorarios del Delegado",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReciboHonorarioDelegadoMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año del Periodo"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes (suma de imp_bruto)",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Renta CIP (25%)"
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU (5%)",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común (10%)",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto Honorario"
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de RH"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios Mensual del Delegado",
                "verbose_name_plural": "Recibos de Honorarios Mensuales del Delegado",
                "ordering": ["-periodo"],
            },
        ),
        migrations.CreateModel(
            name="ReciboHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.IntegerField(verbose_name="Inspecciones Programadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspección",
                    ),
                ),
                (
                    "inspecciones_mes",
                    models.IntegerField(verbose_name="Inspecciones del Mes"),
                ),
                (
                    "monto_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Bruto del Mes",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                (
                    "saldo_inspecciones",
                    models.IntegerField(verbose_name="Saldo de Inspecciones"),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Sub Total"
                    ),
                ),
                (
                    "tasa_descuento_aplicada",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios del Inspector",
                "verbose_name_plural": "Recibos de Honorarios del Inspector",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReciboHonorarioInspectorMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "numero",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de RH"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Año del Periodo"
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
                (
                    "tasa_descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios Mensual del Inspector",
                "verbose_name_plural": "Recibos de Honorarios Mensuales del Inspector",
                "ordering": ["-periodo"],
            },
        ),
        migrations.CreateModel(
            name="RegistroPagoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Año del Periodo",
                    ),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mes (1-12)",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                (
                    "fecha_registro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Pago del Inspector",
                "verbose_name_plural": "Registros de Pago del Inspector",
                "ordering": ["-periodo", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="RHReparticionEstacional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.PositiveSmallIntegerField(
                        help_text="Año de la repartición (e.g., 2026)",
                        verbose_name="Año del Periodo",
                    ),
                ),
                (
                    "total_fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Suma del fondo_comun de los DetalleHonorarioDelegado relacionados",
                        max_digits=12,
                        verbose_name="Total Fondo Común",
                    ),
                ),
                (
                    "numero_capitulos",
                    models.PositiveSmallIntegerField(
                        help_text="Cantidad de capítulos vinculados a la especialidad en este cálculo",
                        verbose_name="Número de Capítulos",
                    ),
                ),
                (
                    "numero_delegados",
                    models.PositiveSmallIntegerField(
                        help_text="Cantidad de delegados seleccionados",
                        verbose_name="Número de Delegados",
                    ),
                ),
                (
                    "monto_por_participacion",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto por cada delegado o capítulo (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto por Participación",
                    ),
                ),
                (
                    "residual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Diferencia no distribuible (total_fondo_comun - suma de partes)",
                        max_digits=12,
                        verbose_name="Residual",
                    ),
                ),
                (
                    "mes_desde",
                    models.PositiveSmallIntegerField(
                        help_text="Mes inicial del rango de la repartición",
                        verbose_name="Mes Desde (1-12)",
                    ),
                ),
                (
                    "mes_hasta",
                    models.PositiveSmallIntegerField(
                        help_text="Mes final del rango de la repartición",
                        verbose_name="Mes Hasta (1-12)",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Eliminación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Repartición Estacional",
                "verbose_name_plural": "Reparticiones Estacionales",
                "ordering": ["-periodo", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RHReparticionEstacionalCapitulo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto recibido por este capítulo (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Capítulo en Repartición Estacional",
                "verbose_name_plural": "Detalles de Capítulos en Reparticiones Estacionales",
                "ordering": ["reparticion", "capitulo"],
            },
        ),
        migrations.CreateModel(
            name="RHReparticionEstacionalDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Monto recibido por este delegado (4 decimales)",
                        max_digits=14,
                        verbose_name="Monto Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Delegado en Repartición Estacional",
                "verbose_name_plural": "Detalles de Delegados en Reparticiones Estacionales",
                "ordering": ["reparticion", "delegado"],
            },
        ),
        migrations.CreateModel(
            name="TasaDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Tasa",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.25 = 25%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.05 = 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.10 = 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Fondo Común",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de Delegado",
                "verbose_name_plural": "Tasas de Delegado",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="UIT",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "valor",
                    models.IntegerField(
                        help_text="Valor de la UIT en soles",
                        verbose_name="Valor UIT (S/)",
                    ),
                ),
            ],
            options={
                "verbose_name": "UIT",
                "verbose_name_plural": "UIT",
                "ordering": ["-periodo_inicio"],
            },
        ),
    ]
