# Generated by Django 5.2.11 on 2026-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DerechoMinimo",
        ),
        migrations.DeleteModel(
            name="HistoricalDerechoMinimo",
        ),
    ]
