# Generated by Django 5.2.11 on 2026-10-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0001_initial"),
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="liquidacion_delegado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_honorario",
                to="liquidaciones.liquidaciondelegado",
                verbose_name="Liquidacion Delegado",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="liquidacion_por_categoria_visitas",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_honorario",
                to="liquidaciones.liquidacionporcategoriavisitas",
                verbose_name="Liquidacion de Categoria de Visitas",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="escala_descuento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala Descuento",
            ),
        ),
    ]
