# Generated by Django 5.2.11 on 2026-08-16 17:17

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_initial"),
        ("liquidaciones", "0008_move_liquidacioninspector_fk_a_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo de la escala (ej. 'Escala 2026').",
                        max_length=100,
                        null=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala de Descuento de Inspector",
                "verbose_name_plural": "Escalas de Descuento de Inspectores",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEscalaDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre descriptivo de la escala (ej. 'Escala 2026').",
                        max_length=100,
                        null=True,
                        verbose_name="Nombre",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Escala de Descuento de Inspector",
                "verbose_name_plural": "historical Escalas de Descuento de Inspectores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRangoDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Límite inferior del tramo (inclusive).",
                        max_digits=12,
                        verbose_name="Monto Mínimo",
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Límite superior del tramo (exclusivo). Null = sin tope superior.",
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Máximo",
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje de descuento como fracción decimal (ej. 0.15 para 15%).",
                        max_digits=5,
                        verbose_name="Porcentaje de Descuento",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rango de Descuento de Inspector",
                "verbose_name_plural": "historical Rangos de Descuento de Inspectores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReciboHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.PositiveIntegerField(
                        help_text="Cantidad de visitas de la liquidación (cantidad_visitas).",
                        verbose_name="Inspecciones Programadas",
                    ),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="importe_bruto / inspecciones_programadas.",
                        max_digits=12,
                        verbose_name="Costo por Inspección",
                    ),
                ),
                (
                    "inspecciones_mes",
                    models.PositiveIntegerField(
                        help_text="Inspecciones liquidadas en el mes (input del usuario).",
                        verbose_name="Inspecciones del Mes",
                    ),
                ),
                (
                    "monto_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="costo_por_inspeccion * inspecciones_mes.",
                        max_digits=12,
                        verbose_name="Monto Bruto",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Inspecciones ya pagadas. Por ahora siempre 0.",
                        verbose_name="Inspecciones Pagadas",
                    ),
                ),
                (
                    "saldo_inspecciones",
                    models.PositiveIntegerField(
                        help_text="programadas - mes - pagadas.",
                        verbose_name="Saldo de Inspecciones",
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Igual al monto_bruto.",
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tasa_descuento_aplicada",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje del rango vigente según sub_total (fracción decimal).",
                        max_digits=5,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="sub_total * tasa_descuento_aplicada.",
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="sub_total - descuento.",
                        max_digits=12,
                        verbose_name="Honorarios",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "escala_descuento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Escala vigente aplicada al momento del cálculo.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_inspector",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Asociación inspector - liquidación por categoría de visitas (IO).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidacioninspector",
                        verbose_name="Inspector de Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios del Inspector",
                "verbose_name_plural": "historical Recibos de Honorarios de Inspectores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReciboHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_programadas",
                    models.PositiveIntegerField(
                        help_text="Cantidad de visitas de la liquidación (cantidad_visitas).",
                        verbose_name="Inspecciones Programadas",
                    ),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="importe_bruto / inspecciones_programadas.",
                        max_digits=12,
                        verbose_name="Costo por Inspección",
                    ),
                ),
                (
                    "inspecciones_mes",
                    models.PositiveIntegerField(
                        help_text="Inspecciones liquidadas en el mes (input del usuario).",
                        verbose_name="Inspecciones del Mes",
                    ),
                ),
                (
                    "monto_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="costo_por_inspeccion * inspecciones_mes.",
                        max_digits=12,
                        verbose_name="Monto Bruto",
                    ),
                ),
                (
                    "inspecciones_pagadas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Inspecciones ya pagadas. Por ahora siempre 0.",
                        verbose_name="Inspecciones Pagadas",
                    ),
                ),
                (
                    "saldo_inspecciones",
                    models.PositiveIntegerField(
                        help_text="programadas - mes - pagadas.",
                        verbose_name="Saldo de Inspecciones",
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Igual al monto_bruto.",
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tasa_descuento_aplicada",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje del rango vigente según sub_total (fracción decimal).",
                        max_digits=5,
                        verbose_name="Tasa de Descuento Aplicada",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="sub_total * tasa_descuento_aplicada.",
                        max_digits=12,
                        verbose_name="Descuento",
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="sub_total - descuento.",
                        max_digits=12,
                        verbose_name="Honorarios",
                    ),
                ),
                (
                    "escala_descuento",
                    models.ForeignKey(
                        help_text="Escala vigente aplicada al momento del cálculo.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento",
                    ),
                ),
                (
                    "liquidacion_inspector",
                    models.ForeignKey(
                        help_text="Asociación inspector - liquidación por categoría de visitas (IO).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_honorarios",
                        to="liquidaciones.liquidacioninspector",
                        verbose_name="Inspector de Liquidación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios del Inspector",
                "verbose_name_plural": "Recibos de Honorarios de Inspectores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RangoDescuentoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Límite inferior del tramo (inclusive).",
                        max_digits=12,
                        verbose_name="Monto Mínimo",
                    ),
                ),
                (
                    "monto_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Límite superior del tramo (exclusivo). Null = sin tope superior.",
                        max_digits=12,
                        null=True,
                        verbose_name="Monto Máximo",
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Porcentaje de descuento como fracción decimal (ej. 0.15 para 15%).",
                        max_digits=5,
                        verbose_name="Porcentaje de Descuento",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rangos",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango de Descuento de Inspector",
                "verbose_name_plural": "Rangos de Descuento de Inspectores",
                "ordering": ["escala", "monto_minimo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("escala", "monto_minimo"),
                        name="unique_rango_descuento_escala_monto_minimo",
                    )
                ],
            },
        ),
    ]
