# Generated by Django 5.2.11 on 2026-08-14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("finanzas", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReciboHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Subtotal Liquidación",
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Neto Honorario",
                    ),
                ),
                (
                    "honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorario",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_delegado",
                    models.ForeignKey(
                        db_column="liquidacion_delegado_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibo_honorario_history",
                        to="liquidaciones.liquidaciondelegado",
                        verbose_name="Asignación Delegado",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios del Delegado",
                "verbose_name_plural": "historical Recibos de Honorarios del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReciboHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Subtotal Liquidación",
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Neto Honorario",
                    ),
                ),
                (
                    "honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorario",
                    ),
                ),
                (
                    "liquidacion_delegado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibo_honorario",
                        to="liquidaciones.liquidaciondelegado",
                        verbose_name="Asignación Delegado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios del Delegado",
                "verbose_name_plural": "Recibos de Honorarios del Delegado",
                "ordering": ["-created_at"],
            },
        ),
    ]
