# Generated by Django 5.2.11 on 2026-08-16 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_escaladescuentoinspector_and_more"),
        ("liquidaciones", "0008_move_liquidacioninspector_fk_a_tipo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escaladescuentoinspector",
            options={
                "ordering": ["-periodo_inicio"],
                "verbose_name": "Escala de Descuento del Inspector",
                "verbose_name_plural": "Escalas de Descuento del Inspector",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalescaladescuentoinspector",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Escala de Descuento del Inspector",
                "verbose_name_plural": "historical Escalas de Descuento del Inspector",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrangodescuentoinspector",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Rango de Descuento del Inspector",
                "verbose_name_plural": "historical Rangos de Descuento del Inspector",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrecibohonorarioinspector",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Recibo de Honorarios del Inspector",
                "verbose_name_plural": "historical Recibos de Honorarios del Inspector",
            },
        ),
        migrations.AlterModelOptions(
            name="rangodescuentoinspector",
            options={
                "ordering": ["escala", "monto_minimo"],
                "verbose_name": "Rango de Descuento del Inspector",
                "verbose_name_plural": "Rangos de Descuento del Inspector",
            },
        ),
        migrations.AlterModelOptions(
            name="recibohonorarioinspector",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recibo de Honorarios del Inspector",
                "verbose_name_plural": "Recibos de Honorarios del Inspector",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rangodescuentoinspector",
            name="unique_rango_descuento_escala_monto_minimo",
        ),
        migrations.AlterField(
            model_name="escaladescuentoinspector",
            name="nombre",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nombre de la Escala",
            ),
        ),
        migrations.AlterField(
            model_name="historicalescaladescuentoinspector",
            name="nombre",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nombre de la Escala",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrangodescuentoinspector",
            name="escala",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrangodescuentoinspector",
            name="monto_maximo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto Máximo (null = sin tope)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrangodescuentoinspector",
            name="monto_minimo",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrangodescuentoinspector",
            name="porcentaje_descuento",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Ej: 0.15 = 15%",
                max_digits=5,
                verbose_name="Porcentaje de Descuento",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="costo_por_inspeccion",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Costo por Inspección"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Descuento"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="escala_descuento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala de Descuento Aplicada",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="honorarios",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Honorarios a Pagar"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="inspecciones_mes",
            field=models.IntegerField(verbose_name="Inspecciones del Mes"),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="inspecciones_pagadas",
            field=models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="inspecciones_programadas",
            field=models.IntegerField(verbose_name="Inspecciones Programadas"),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="liquidacion_inspector",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.liquidacioninspector",
                verbose_name="Asociación Inspector - IO",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="monto_bruto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto Bruto del Mes"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="saldo_inspecciones",
            field=models.IntegerField(verbose_name="Saldo de Inspecciones"),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Sub Total"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspector",
            name="tasa_descuento_aplicada",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=5,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
        migrations.AlterField(
            model_name="rangodescuentoinspector",
            name="escala",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rangos",
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala",
            ),
        ),
        migrations.AlterField(
            model_name="rangodescuentoinspector",
            name="monto_maximo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Monto Máximo (null = sin tope)",
            ),
        ),
        migrations.AlterField(
            model_name="rangodescuentoinspector",
            name="monto_minimo",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="rangodescuentoinspector",
            name="porcentaje_descuento",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Ej: 0.15 = 15%",
                max_digits=5,
                verbose_name="Porcentaje de Descuento",
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="costo_por_inspeccion",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Costo por Inspección"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="descuento",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Descuento"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="escala_descuento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos",
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala de Descuento Aplicada",
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="honorarios",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Honorarios a Pagar"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="inspecciones_mes",
            field=models.IntegerField(verbose_name="Inspecciones del Mes"),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="inspecciones_pagadas",
            field=models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="inspecciones_programadas",
            field=models.IntegerField(verbose_name="Inspecciones Programadas"),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="liquidacion_inspector",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibo_honorario",
                to="liquidaciones.liquidacioninspector",
                verbose_name="Asociación Inspector - IO",
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="monto_bruto",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto Bruto del Mes"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="saldo_inspecciones",
            field=models.IntegerField(verbose_name="Saldo de Inspecciones"),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Sub Total"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspector",
            name="tasa_descuento_aplicada",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=5,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
        migrations.AddConstraint(
            model_name="rangodescuentoinspector",
            constraint=models.UniqueConstraint(
                fields=("escala", "monto_minimo"),
                name="unique_rango_descuento_inspector",
            ),
        ),
    ]
