# Generated by Django 5.2.11 on 2026-08-21 19:54

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0004_alter_escaladescuentoinspector_options_and_more"),
        ("liquidaciones", "0011_create_rh_inspector_mensual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReciboHonorarioInspectorMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "escala_descuento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento Aplicada",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.inspector",
                        verbose_name="Inspector",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios Mensual del Inspector",
                "verbose_name_plural": "historical Recibos de Honorarios Mensuales del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRegistroPagoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_por_categoria_visitas",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidacionporcategoriavisitas",
                        verbose_name="Liquidacion de Categoria de Visitas",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Registro de Pago del Inspector",
                "verbose_name_plural": "historical Registros de Pago del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReciboHonorarioInspectorMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes",
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Descuento"
                    ),
                ),
                (
                    "honorarios",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Honorarios a Pagar",
                    ),
                ),
                (
                    "escala_descuento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_mensuales",
                        to="finanzas.escaladescuentoinspector",
                        verbose_name="Escala de Descuento Aplicada",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_mensuales",
                        to="liquidaciones.inspector",
                        verbose_name="Inspector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios Mensual del Inspector",
                "verbose_name_plural": "Recibos de Honorarios Mensuales del Inspector",
                "ordering": ["-periodo"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDetalleHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_liquidadas",
                    models.IntegerField(verbose_name="Inspecciones Liquidadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspeccion",
                    ),
                ),
                (
                    "monto_contribuido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Contribuido",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_por_categoria_visitas",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidacionporcategoriavisitas",
                        verbose_name="Liquidacion de Categoria de Visitas",
                    ),
                ),
                (
                    "recibo_mensual",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.recibohonorarioinspectormensual",
                        verbose_name="Recibo Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Honorario del Inspector",
                "verbose_name_plural": "historical Detalles de Honorarios del Inspector",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DetalleHonorarioInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "inspecciones_liquidadas",
                    models.IntegerField(verbose_name="Inspecciones Liquidadas"),
                ),
                (
                    "costo_por_inspeccion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Costo por Inspeccion",
                    ),
                ),
                (
                    "monto_contribuido",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto Contribuido",
                    ),
                ),
                (
                    "liquidacion_por_categoria_visitas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_honorario",
                        to="liquidaciones.liquidacionporcategoriavisitas",
                        verbose_name="Liquidacion de Categoria de Visitas",
                    ),
                ),
                (
                    "recibo_mensual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="finanzas.recibohonorarioinspectormensual",
                        verbose_name="Recibo Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Honorario del Inspector",
                "verbose_name_plural": "Detalles de Honorarios del Inspector",
                "ordering": ["recibo_mensual", "liquidacion_por_categoria_visitas"],
            },
        ),
        migrations.CreateModel(
            name="RegistroPagoInspector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "inspecciones_pagadas",
                    models.IntegerField(default=0, verbose_name="Inspecciones Pagadas"),
                ),
                (
                    "liquidacion_por_categoria_visitas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_pago",
                        to="liquidaciones.liquidacionporcategoriavisitas",
                        verbose_name="Liquidacion de Categoria de Visitas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Pago del Inspector",
                "verbose_name_plural": "Registros de Pago del Inspector",
                "ordering": ["-periodo"],
            },
        ),
        migrations.AddConstraint(
            model_name="recibohonorarioinspectormensual",
            constraint=models.UniqueConstraint(
                fields=("inspector", "periodo"), name="unique_rh_inspector_mensual"
            ),
        ),
        migrations.AddConstraint(
            model_name="registropagoinspector",
            constraint=models.UniqueConstraint(
                fields=("liquidacion_por_categoria_visitas", "periodo"),
                name="unique_registro_pago_inspector",
            ),
        ),
    ]
