# Generated by Django 5.2.11 on 2026-08-24

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0005_create_rh_inspector_mensual"),
        ("liquidaciones", "0011_create_rh_inspector_mensual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReciboHonorarioDelegadoMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes (suma de imp_bruto)",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Renta CIP (25%)",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU (5%)",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común (10%)",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Neto Honorario",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Recibo de Honorarios Mensual del Delegado",
                "verbose_name_plural": "historical Recibos de Honorarios Mensuales del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReciboHonorarioDelegadoMensual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(max_length=7, verbose_name="Periodo (YYYY-MM)"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sub Total del Mes (suma de imp_bruto)",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Renta CIP (25%)",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Aporte CODEMU (5%)",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Fondo Común (10%)",
                    ),
                ),
                (
                    "neto_honorario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Neto Honorario",
                    ),
                ),
                (
                    "delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos_mensuales",
                        to="liquidaciones.delegado",
                        verbose_name="Delegado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recibo de Honorarios Mensual del Delegado",
                "verbose_name_plural": "Recibos de Honorarios Mensuales del Delegado",
                "ordering": ["-periodo"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDetalleHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto (del detalle porcentual)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liquidacion_delegado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="liquidaciones.liquidaciondelegado",
                        verbose_name="Liquidacion Delegado",
                    ),
                ),
                (
                    "recibo_mensual",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finanzas.recibohonorariodelegadomensual",
                        verbose_name="Recibo Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Detalle de Honorario del Delegado",
                "verbose_name_plural": "historical Detalles de Honorarios del Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DetalleHonorarioDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "imp_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Importe Bruto (del detalle porcentual)",
                    ),
                ),
                (
                    "liquidacion_delegado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_honorario",
                        to="liquidaciones.liquidaciondelegado",
                        verbose_name="Liquidacion Delegado",
                    ),
                ),
                (
                    "recibo_mensual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="finanzas.recibohonorariodelegadomensual",
                        verbose_name="Recibo Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Honorario del Delegado",
                "verbose_name_plural": "Detalles de Honorarios del Delegado",
                "ordering": ["recibo_mensual", "liquidacion_delegado"],
            },
        ),
        migrations.AddConstraint(
            model_name="recibohonorariodelegadomensual",
            constraint=models.UniqueConstraint(
                fields=("delegado", "periodo"),
                name="unique_rh_delegado_mensual",
            ),
        ),
    ]
