# Generated by Django 5.2.12 on 2026-08-26 20:05

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0006_create_rh_delegado_mensual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTasaDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Tasa",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.25 = 25%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.05 = 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.10 = 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Fondo Común",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tasa de Delegado",
                "verbose_name_plural": "historical Tasas de Delegado",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TasaDelegado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nombre de la Tasa",
                    ),
                ),
                (
                    "renta_cip",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.25 = 25%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Renta CIP",
                    ),
                ),
                (
                    "aporte_codemu",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.05 = 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Aporte CODEMU",
                    ),
                ),
                (
                    "fondo_comun",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fracción decimal (ej. 0.10 = 10%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Tasa Fondo Común",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de Delegado",
                "verbose_name_plural": "Tasas de Delegado",
                "ordering": ["-periodo_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("periodo_fin__isnull", True)),
                        fields=("periodo_inicio",),
                        name="unique_tasa_delegado_vigente_periodo_inicio",
                    )
                ],
            },
        ),
    ]
