# Generated by Django 5.2.11 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0007_create_tasa_delegado"),
        ("liquidaciones", "0030_liquidaciondelegado_delegado_operacion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add FK to DelegadoOperacion on ReciboHonorarioDelegadoMensual
        migrations.AddField(
            model_name="recibohonorariodelegadomensual",
            name="delegado_operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos_mensuales",
                to="liquidaciones.delegadooperacion",
                verbose_name="Delegado Operatividad",
            ),
        ),
        # Add FK to DelegadoOperacion on HistoricalReciboHonorarioDelegadoMensual
        migrations.AddField(
            model_name="historicalrecibohonorariodelegadomensual",
            name="delegado_operacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.delegadooperacion",
                verbose_name="Delegado Operatividad",
            ),
        ),
        # Remove old unique constraint on (delegado, periodo)
        migrations.RemoveConstraint(
            model_name="recibohonorariodelegadomensual",
            name="unique_rh_delegado_mensual",
        ),
        # Add new conditional unique constraints
        # When delegado_operacion is NOT NULL: unique on (delegado_operacion, periodo)
        migrations.AddConstraint(
            model_name="recibohonorariodelegadomensual",
            constraint=models.UniqueConstraint(
                fields=("delegado_operacion", "periodo"),
                name="unique_rh_delegado_mensual",
                condition=models.Q(delegado_operacion__isnull=False),
            ),
        ),
        # When delegado_operacion IS NULL: unique on (delegado, periodo) - legacy fallback
        migrations.AddConstraint(
            model_name="recibohonorariodelegadomensual",
            constraint=models.UniqueConstraint(
                fields=("delegado", "periodo"),
                name="unique_rh_delegado_mensual_legacy",
                condition=models.Q(delegado_operacion__isnull=True),
            ),
        ),
    ]
