# Generated by Django 5.2.11 on 2026-09-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0009_remove_rh_delegado_mensual_unique_constraints"),
        (
            "liquidaciones",
            "0033_historicalliquidacioninspector_inspector_operacion_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recibohonorarioinspectormensual",
            name="unique_rh_inspector_mensual",
        ),
        migrations.AddField(
            model_name="historicalrecibohonorarioinspectormensual",
            name="inspector_operacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.inspectoroperacion",
                verbose_name="Inspector de Operación",
            ),
        ),
        migrations.AddField(
            model_name="recibohonorarioinspectormensual",
            name="inspector_operacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recibos_honorario_mensual",
                to="liquidaciones.inspectoroperacion",
                verbose_name="Inspector de Operación",
            ),
        ),
    ]
