# Generated by Django 5.2.12 on 2026-09-03

import django.db.models.deletion
from django.db import migrations, models


def delete_global_tasas(apps, schema_editor):
    """Elimina la tasa de delegado global legacy (sin tipo_liquidacion).

    La fila única global (tipo NULL) deja de ser válida: ahora la tasa es
    obligatoria por tipo de liquidación. Se borra y se vuelve a sembrar
    por tipo (una por cada uno de los 6 TipoLiquidacion).
    """
    TasaDelegado = apps.get_model("finanzas", "TasaDelegado")
    TasaDelegado.objects.filter(tipo_liquidacion__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0010_remove_recibohonorarioinspectormensual_unique_rh_inspector_mensual_and_more",
        ),
        (
            "liquidaciones",
            "0033_historicalliquidacioninspector_inspector_operacion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltasadelegado",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        # Añadir como nullable primero — puede existir la fila global legacy.
        migrations.AddField(
            model_name="tasadelegado",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasas_delegado",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        # Borrar la fila global legacy (tipo NULL) antes de forzar NOT NULL.
        migrations.RunPython(delete_global_tasas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tasadelegado",
            name="tipo_liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasas_delegado",
                to="liquidaciones.tipoliquidacion",
                verbose_name="Tipo de Liquidación",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="tasadelegado",
            name="unique_tasa_delegado_vigente_periodo_inicio",
        ),
        migrations.AddConstraint(
            model_name="tasadelegado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("periodo_fin__isnull", True)),
                fields=("tipo_liquidacion", "periodo_inicio"),
                name="unique_tasa_delegado_vigente_por_tipo",
            ),
        ),
    ]