# Generated by Django 5.2.11 on 2026-09-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0011_tasa_delegado_tipo_liquidacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="aporte_codemu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aporte CODEMU",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="fondo_comun",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Fondo Común",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="neto_honorario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Neto Honorario",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="renta_cip",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Renta CIP",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Sub Total",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorariodelegado",
            name="tasa_delegado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.tasadelegado",
                verbose_name="Tasa Delegado",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="aporte_codemu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aporte CODEMU",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="fondo_comun",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Fondo Común",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="neto_honorario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Neto Honorario",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="renta_cip",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Renta CIP",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="sub_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Sub Total",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorariodelegado",
            name="tasa_delegado",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finanzas.tasadelegado",
                verbose_name="Tasa Delegado",
            ),
        ),
        migrations.AddField(
            model_name="historicalrecibohonorariodelegadomensual",
            name="tasa_delegado",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finanzas.tasadelegado",
                verbose_name="Tasa Delegado",
            ),
        ),
        migrations.AddField(
            model_name="recibohonorariodelegadomensual",
            name="tasa_delegado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.tasadelegado",
                verbose_name="Tasa Delegado",
            ),
        ),
    ]
