# Generated by Django 5.2.11 on 2026-09-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0012_detallehonorariodelegado_aporte_codemu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="escala_descuento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala Descuento",
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="honorarios",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="importe_bruto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="inspecciones_pagadas_hasta_mes_anterior",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="inspecciones_programadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="saldo_restante",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="detallehonorarioinspector",
            name="tasa_descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=7,
                null=True,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="escala_descuento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="finanzas.escaladescuentoinspector",
                verbose_name="Escala Descuento",
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="honorarios",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="importe_bruto",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="inspecciones_pagadas_hasta_mes_anterior",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="inspecciones_programadas",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="saldo_restante",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldetallehonorarioinspector",
            name="tasa_descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=7,
                null=True,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
        migrations.AddField(
            model_name="historicalrecibohonorariodelegadomensual",
            name="numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de RH"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecibohonorarioinspectormensual",
            name="numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de RH"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecibohonorarioinspectormensual",
            name="tasa_descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=7,
                null=True,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
        migrations.AddField(
            model_name="recibohonorariodelegadomensual",
            name="numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de RH"
            ),
        ),
        migrations.AddField(
            model_name="recibohonorarioinspectormensual",
            name="numero",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número de RH"
            ),
        ),
        migrations.AddField(
            model_name="recibohonorarioinspectormensual",
            name="tasa_descuento",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=7,
                null=True,
                verbose_name="Tasa de Descuento Aplicada",
            ),
        ),
    ]
