# Generated by Django 5.2.11 on 2026-09-07 20:51

from django.db import migrations, models


def backfill_periodo_mes(apps, schema_editor):
    """Convierte periodo 'YYYY-MM' (CharField) en periodo (año int) + mes (int)."""
    for model_name in (
        "ReciboHonorarioDelegadoMensual",
        "ReciboHonorarioInspectorMensual",
    ):
        Model = apps.get_model("finanzas", model_name)
        for obj in Model.objects.exclude(periodo__isnull=True).exclude(periodo=""):
            try:
                year, month = (int(p) for p in str(obj.periodo).split("-"))
                obj.mes = month
                obj.periodo = year
                obj.save(update_fields=["periodo", "mes"])
            except (ValueError, TypeError):
                obj.periodo = None
                obj.save(update_fields=["periodo"])


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0013_detallehonorarioinspector_descuento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecibohonorariodelegadomensual",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
            ),
        ),
        migrations.AddField(
            model_name="historicalrecibohonorarioinspectormensual",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
            ),
        ),
        migrations.AddField(
            model_name="recibohonorariodelegadomensual",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
            ),
        ),
        migrations.AddField(
            model_name="recibohonorarioinspectormensual",
            name="mes",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Mes del Periodo (1-12)"
            ),
        ),
        migrations.RunPython(backfill_periodo_mes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recibohonorariodelegadomensual",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Año del Periodo"
            ),
        ),
        migrations.AlterField(
            model_name="recibohonorarioinspectormensual",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Año del Periodo"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorariodelegadomensual",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Año del Periodo"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrecibohonorarioinspectormensual",
            name="periodo",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Año del Periodo"
            ),
        ),
    ]