# Generated by Django 5.2.11 on 2026-10-05 09:04

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alcalde",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Alcalde"),
                ),
            ],
            options={
                "verbose_name": "Alcalde",
                "verbose_name_plural": "Alcaldes",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del banco",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="DNI"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["nombres", "apellidos"],
            },
        ),
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("RUC", "RUC"), ("DNI", "DNI")],
                        help_text="RUC para instituciones, DNI para personas naturales.",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="RUC (11 dígitos) o DNI (8 dígitos).",
                        max_length=11,
                        unique=True,
                        verbose_name="Número de Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad",
                "verbose_name_plural": "Entidades",
                "ordering": ["numero_documento"],
            },
        ),
        migrations.CreateModel(
            name="GerenteUrbano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Gerente Urbano"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerente Urbano",
                "verbose_name_plural": "Gerentes Urbanos",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAlcalde",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Alcalde"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Alcalde",
                "verbose_name_plural": "historical Alcaldes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del banco",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Banco",
                "verbose_name_plural": "historical Bancos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContacto",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="DNI"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contacto",
                "verbose_name_plural": "historical Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContactoBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal del banco.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en el banco.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Banco - Contacto",
                "verbose_name_plural": "historical Bancos - Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContactoMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la municipalidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la municipalidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Municipalidad - Contacto",
                "verbose_name_plural": "historical Municipalidades - Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEntidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("RUC", "RUC"), ("DNI", "DNI")],
                        help_text="RUC para instituciones, DNI para personas naturales.",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="RUC (11 dígitos) o DNI (8 dígitos).",
                        max_length=11,
                        verbose_name="Número de Documento",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entidad",
                "verbose_name_plural": "historical Entidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGerenteUrbano",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Periodo de Inicio")),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo de Fin"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Gerente Urbano"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Gerente Urbano",
                "verbose_name_plural": "historical Gerentes Urbanos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la municipalidad.",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Municipalidad",
                "verbose_name_plural": "historical Municipalidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Municipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la municipalidad.",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipalidad",
                "verbose_name_plural": "Municipalidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UbigeoDepartamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del departamento (e.g. LIMA, ANCASH)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UbigeoDistrito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del distrito (e.g. MIRAFLORES, BAGUA)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "ubigeo",
                    models.CharField(
                        db_index=True,
                        help_text="Código ubigeo de 6 dígitos (e.g. 150101)",
                        max_length=6,
                        unique=True,
                        verbose_name="Código Ubigeo",
                    ),
                ),
                (
                    "inei",
                    models.CharField(
                        blank=True,
                        help_text="Código INEI alternativo (si existe)",
                        max_length=6,
                        null=True,
                        verbose_name="Código INEI",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "ordering": [
                    "provincia__departamento__nombre",
                    "provincia__nombre",
                    "nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="UbigeoProvincia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre de la provincia (e.g. LIMA, BAGUA)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["departamento__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContactoBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal del banco.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en el banco.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="entidades.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bancos",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco - Contacto",
                "verbose_name_plural": "Bancos - Contactos",
                "ordering": ["-principal", "banco__nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContactoMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la municipalidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la municipalidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipalidades",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipalidad - Contacto",
                "verbose_name_plural": "Municipalidades - Contactos",
                "ordering": ["-principal", "municipalidad__nombre"],
            },
        ),
    ]
