# Generated by Django 5.2.11 on 2026-06-18 11:25

import django.db.models.deletion
import simple_history.models
import utils.ubigeo_schema
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del banco",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["nombres", "apellidos"],
            },
        ),
        migrations.CreateModel(
            name="Entidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("RUC", "RUC"), ("DNI", "DNI")],
                        help_text="RUC para instituciones, DNI para personas naturales.",
                        max_length=3,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="RUC (11 dígitos) o DNI (8 dígitos).",
                        max_length=11,
                        unique=True,
                        verbose_name="Número de Documento",
                    ),
                ),
                (
                    "tipo_contribuyente",
                    models.CharField(
                        blank=True,
                        help_text="Todos los tipos de contribuyente posibles (opcional).",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Contribuyente",
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True,
                        help_text="Para personas naturales. En blanco para instituciones.",
                        max_length=255,
                        null=True,
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True,
                        help_text="Para personas naturales. En blanco para instituciones.",
                        max_length=255,
                        null=True,
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Para instituciones. En blanco para personas naturales.",
                        max_length=255,
                        null=True,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Comercial",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dirección"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
            ],
            options={
                "verbose_name": "Entidad",
                "verbose_name_plural": "Entidades",
                "ordering": ["razon_social", "apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="Municipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la municipalidad.",
                        max_length=10,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
            ],
            options={
                "verbose_name": "Municipalidad",
                "verbose_name_plural": "Municipalidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UbigeoDepartamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del departamento (e.g. LIMA, ANCASH)",
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="UbigeoDistrito",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre del distrito (e.g. MIRAFLORES, BAGUA)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "ubigeo",
                    models.CharField(
                        db_index=True,
                        help_text="Código ubigeo de 6 dígitos (e.g. 150101)",
                        max_length=6,
                        unique=True,
                        verbose_name="Código Ubigeo",
                    ),
                ),
                (
                    "inei",
                    models.CharField(
                        blank=True,
                        help_text="Código INEI alternativo (si existe)",
                        max_length=6,
                        null=True,
                        verbose_name="Código INEI",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distrito",
                "verbose_name_plural": "Distritos",
                "ordering": [
                    "provincia__departamento__nombre",
                    "provincia__nombre",
                    "nombre",
                ],
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[],
            options={
                "verbose_name": "Institución",
                "verbose_name_plural": "Instituciones",
                "ordering": ["razon_social"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.entidad",),
        ),
        migrations.CreateModel(
            name="PersonaNatural",
            fields=[],
            options={
                "verbose_name": "Persona Natural",
                "verbose_name_plural": "Personas Naturales",
                "ordering": ["apellidos", "nombres"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.entidad",),
        ),
        migrations.CreateModel(
            name="HistoricalBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del banco",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Banco",
                "verbose_name_plural": "historical Bancos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContacto",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nombres"
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "celular",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Dirección"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contacto",
                "verbose_name_plural": "historical Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContactoBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal del banco.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en el banco.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Banco - Contacto",
                "verbose_name_plural": "historical Bancos - Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContactoEntidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la entidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la entidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.entidad",
                        verbose_name="Entidad",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entidad - Contacto",
                "verbose_name_plural": "historical Entidades - Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalGerenteUrbano",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Gerente Urbano"
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio del Período"
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin del Período"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Gerente Urbano",
                "verbose_name_plural": "historical Gerentes Urbanos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContactoMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la municipalidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la municipalidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Municipalidad - Contacto",
                "verbose_name_plural": "historical Municipalidades - Contactos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAlcalde",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Alcalde"),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio del Período"
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin del Período"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Alcalde",
                "verbose_name_plural": "historical Alcaldes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GerenteUrbano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Gerente Urbano"
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio del Período"
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin del Período"
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gerentes_urbanos",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerente Urbano",
                "verbose_name_plural": "Gerentes Urbanos",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Alcalde",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del Alcalde"),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio del Período"
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin del Período"
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alcaldes",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alcalde",
                "verbose_name_plural": "Alcaldes",
                "ordering": ["-periodo_inicio"],
            },
        ),
        migrations.CreateModel(
            name="MunicipalidadDistrital",
            fields=[],
            options={
                "verbose_name": "Municipalidad Distrital",
                "verbose_name_plural": "Municipalidades Distritales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.municipalidad",),
        ),
        migrations.CreateModel(
            name="MunicipalidadProvincial",
            fields=[],
            options={
                "verbose_name": "Municipalidad Provincial",
                "verbose_name_plural": "Municipalidades Provinciales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.municipalidad",),
        ),
        migrations.AddField(
            model_name="municipalidad",
            name="distrito",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_distrito_flat_choices_callable,
                help_text="Distrito asociado a la municipalidad. Solo si es municipalidad distrital.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipalidades",
                to="entidades.ubigeodistrito",
                verbose_name="Distrito",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEntidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("RUC", "RUC"), ("DNI", "DNI")],
                        help_text="RUC para instituciones, DNI para personas naturales.",
                        max_length=3,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        db_index=True,
                        help_text="RUC (11 dígitos) o DNI (8 dígitos).",
                        max_length=11,
                        verbose_name="Número de Documento",
                    ),
                ),
                (
                    "tipo_contribuyente",
                    models.CharField(
                        blank=True,
                        help_text="Todos los tipos de contribuyente posibles (opcional).",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Contribuyente",
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True,
                        help_text="Para personas naturales. En blanco para instituciones.",
                        max_length=255,
                        null=True,
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        blank=True,
                        help_text="Para personas naturales. En blanco para instituciones.",
                        max_length=255,
                        null=True,
                        verbose_name="Apellidos",
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Para instituciones. En blanco para personas naturales.",
                        max_length=255,
                        null=True,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre Comercial",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dirección"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.ubigeodistrito",
                        verbose_name="Distrito",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entidad",
                "verbose_name_plural": "historical Entidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="entidad",
            name="distrito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entidades",
                to="entidades.ubigeodistrito",
                verbose_name="Distrito",
            ),
        ),
        migrations.CreateModel(
            name="UbigeoProvincia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre de la provincia (e.g. LIMA, BAGUA)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provincias",
                        to="entidades.ubigeodepartamento",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["departamento__nombre", "nombre"],
            },
        ),
        migrations.AddField(
            model_name="ubigeodistrito",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distritos",
                to="entidades.ubigeoprovincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AddField(
            model_name="municipalidad",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_provincia_choices_callable,
                help_text="Provincia asociada a la municipalidad. Solo si es municipalidad provincial.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipalidades",
                to="entidades.ubigeoprovincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Última actualización"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único de la municipalidad.",
                        max_length=10,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        blank=True,
                        choices=utils.ubigeo_schema.get_distrito_flat_choices_callable,
                        db_constraint=False,
                        help_text="Distrito asociado a la municipalidad. Solo si es municipalidad distrital.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.ubigeodistrito",
                        verbose_name="Distrito",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        choices=utils.ubigeo_schema.get_provincia_choices_callable,
                        db_constraint=False,
                        help_text="Provincia asociada a la municipalidad. Solo si es municipalidad provincial.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="entidades.ubigeoprovincia",
                        verbose_name="Provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Municipalidad",
                "verbose_name_plural": "historical Municipalidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContactoBanco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal del banco.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en el banco.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "banco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="entidades.banco",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bancos",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco - Contacto",
                "verbose_name_plural": "Bancos - Contactos",
                "ordering": ["-principal", "banco__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("banco", "contacto"), name="unique_banco_contacto"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactoEntidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la entidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la entidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entidades",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="entidades.entidad",
                        verbose_name="Entidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad - Contacto",
                "verbose_name_plural": "Entidades - Contactos",
                "ordering": [
                    "-principal",
                    "entidad__razon_social",
                    "entidad__apellidos",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entidad", "contacto"), name="unique_entidad_contacto"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactoMunicipalidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "principal",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el contacto principal de la municipalidad.",
                        verbose_name="¿Principal?",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre el rol de este contacto en la municipalidad.",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
                (
                    "contacto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipalidades",
                        to="entidades.contacto",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "municipalidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="entidades.municipalidad",
                        verbose_name="Municipalidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipalidad - Contacto",
                "verbose_name_plural": "Municipalidades - Contactos",
                "ordering": ["-principal", "municipalidad__nombre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("municipalidad", "contacto"),
                        name="unique_municipalidad_contacto",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ubigeoprovincia",
            constraint=models.UniqueConstraint(
                fields=("departamento", "nombre"), name="unique_departamento_provincia"
            ),
        ),
        migrations.AddConstraint(
            model_name="ubigeodistrito",
            constraint=models.UniqueConstraint(
                fields=("provincia", "nombre"), name="unique_provincia_distrito"
            ),
        ),
    ]
