# Generated by Django 5.2.12 on 2026-06-09 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalbanco',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbancocontacto',
            name='banco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='historicalbancocontacto',
            name='contacto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.contacto', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='historicalbancocontacto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontacto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalempresacontacto',
            name='contacto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.contacto', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='historicalempresacontacto',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalempresacontacto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmunicipalidad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmunicipalidadcontacto',
            name='contacto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.contacto', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='historicalmunicipalidadcontacto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmunicipalidadcontacto',
            name='municipalidad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='entidades.municipalidad', verbose_name='Municipalidad'),
        ),
        migrations.AddField(
            model_name='municipalidadcontacto',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipalidades', to='entidades.contacto', verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='municipalidadcontacto',
            name='municipalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='entidades.municipalidad', verbose_name='Municipalidad'),
        ),
        migrations.AddConstraint(
            model_name='bancocontacto',
            constraint=models.UniqueConstraint(fields=('banco', 'contacto'), name='unique_banco_contacto'),
        ),
        migrations.AddConstraint(
            model_name='empresacontacto',
            constraint=models.UniqueConstraint(fields=('empresa', 'contacto'), name='unique_empresa_contacto'),
        ),
        migrations.AddConstraint(
            model_name='municipalidadcontacto',
            constraint=models.UniqueConstraint(fields=('municipalidad', 'contacto'), name='unique_municipalidad_contacto'),
        ),
    ]
