# Generated by Django 5.2.11 on 2026-06-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacto",
            name="dni",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="DNI"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontacto",
            name="dni",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="DNI"
            ),
        ),
    ]
