# Generated by Django 5.2.11 on 2026-08-07 12:16

import django.db.models.deletion
import utils.ubigeo_schema
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalalcalde",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbanco",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontacto",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactobanco",
            name="banco",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.banco",
                verbose_name="Banco",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactobanco",
            name="contacto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.contacto",
                verbose_name="Contacto",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactobanco",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactomunicipalidad",
            name="contacto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.contacto",
                verbose_name="Contacto",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactomunicipalidad",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalentidad",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalgerenteurbano",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmunicipalidad",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalgerenteurbano",
            name="municipalidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontactomunicipalidad",
            name="municipalidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="historicalalcalde",
            name="municipalidad",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="gerenteurbano",
            name="municipalidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gerentes_urbanos",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="contactomunicipalidad",
            name="municipalidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contactos",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.AddField(
            model_name="alcalde",
            name="municipalidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alcaldes",
                to="entidades.municipalidad",
                verbose_name="Municipalidad",
            ),
        ),
        migrations.CreateModel(
            name="MunicipalidadDistrital",
            fields=[],
            options={
                "verbose_name": "Municipalidad Distrital",
                "verbose_name_plural": "Municipalidades Distritales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.municipalidad",),
        ),
        migrations.CreateModel(
            name="MunicipalidadProvincial",
            fields=[],
            options={
                "verbose_name": "Municipalidad Provincial",
                "verbose_name_plural": "Municipalidades Provinciales",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("entidades.municipalidad",),
        ),
        migrations.AddField(
            model_name="municipalidad",
            name="distrito",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_distrito_flat_choices_callable,
                help_text="Distrito asociado a la municipalidad. Solo si es municipalidad distrital.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipalidades",
                to="entidades.ubigeodistrito",
                verbose_name="Distrito",
            ),
        ),
        migrations.AddField(
            model_name="historicalmunicipalidad",
            name="distrito",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_distrito_flat_choices_callable,
                db_constraint=False,
                help_text="Distrito asociado a la municipalidad. Solo si es municipalidad distrital.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.ubigeodistrito",
                verbose_name="Distrito",
            ),
        ),
        migrations.AddField(
            model_name="ubigeoprovincia",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provincias",
                to="entidades.ubigeodepartamento",
                verbose_name="Departamento",
            ),
        ),
        migrations.AddField(
            model_name="ubigeodistrito",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distritos",
                to="entidades.ubigeoprovincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AddField(
            model_name="municipalidad",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_provincia_choices_callable,
                help_text="Provincia asociada a la municipalidad. Solo si es municipalidad provincial.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="municipalidades",
                to="entidades.ubigeoprovincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AddField(
            model_name="historicalmunicipalidad",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                choices=utils.ubigeo_schema.get_provincia_choices_callable,
                db_constraint=False,
                help_text="Provincia asociada a la municipalidad. Solo si es municipalidad provincial.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="entidades.ubigeoprovincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactobanco",
            constraint=models.UniqueConstraint(
                fields=("banco", "contacto"), name="unique_banco_contacto"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactomunicipalidad",
            constraint=models.UniqueConstraint(
                fields=("municipalidad", "contacto"),
                name="unique_municipalidad_contacto",
            ),
        ),
        migrations.AddConstraint(
            model_name="ubigeoprovincia",
            constraint=models.UniqueConstraint(
                fields=("departamento", "nombre"), name="unique_departamento_provincia"
            ),
        ),
        migrations.AddConstraint(
            model_name="ubigeodistrito",
            constraint=models.UniqueConstraint(
                fields=("provincia", "nombre"), name="unique_provincia_distrito"
            ),
        ),
    ]
