# Generated by Django 5.2.11 on 2026-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entidad",
            name="tipo_documento",
            field=models.CharField(
                choices=[("RUC", "RUC"), ("DNI", "DNI")],
                help_text="RUC para instituciones, DNI para personas naturales.",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterField(
            model_name="historicalentidad",
            name="tipo_documento",
            field=models.CharField(
                choices=[("RUC", "RUC"), ("DNI", "DNI")],
                help_text="RUC para instituciones, DNI para personas naturales.",
                max_length=20,
                verbose_name="Tipo de Documento",
            ),
        ),
    ]
