# Generated by Django 5.2.11 on 2026-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0002_contacto_dni_historicalcontacto_dni"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactoentidad",
            options={
                "ordering": ["-principal", "entidad__razon_social"],
                "verbose_name": "Entidad - Contacto",
                "verbose_name_plural": "Entidades - Contactos",
            },
        ),
        migrations.AlterModelOptions(
            name="entidad",
            options={
                "ordering": ["razon_social"],
                "verbose_name": "Entidad",
                "verbose_name_plural": "Entidades",
            },
        ),
        migrations.AlterModelOptions(
            name="personanatural",
            options={
                "ordering": ["razon_social"],
                "verbose_name": "Persona Natural",
                "verbose_name_plural": "Personas Naturales",
            },
        ),
        migrations.RemoveField(
            model_name="entidad",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="entidad",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="entidad",
            name="distrito",
        ),
        migrations.RemoveField(
            model_name="entidad",
            name="nombres",
        ),
        migrations.RemoveField(
            model_name="historicalentidad",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="historicalentidad",
            name="apellidos",
        ),
        migrations.RemoveField(
            model_name="historicalentidad",
            name="distrito",
        ),
        migrations.RemoveField(
            model_name="historicalentidad",
            name="nombres",
        ),
        migrations.AlterField(
            model_name="entidad",
            name="razon_social",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Para instituciones: razón social. Para personas naturales: nombre completo.",
                max_length=255,
                null=True,
                verbose_name="Razón Social / Nombre Completo",
            ),
        ),
        migrations.AlterField(
            model_name="historicalentidad",
            name="razon_social",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Para instituciones: razón social. Para personas naturales: nombre completo.",
                max_length=255,
                null=True,
                verbose_name="Razón Social / Nombre Completo",
            ),
        ),
    ]
