name: Deploy to Test

on:
  push:
    branches: [alpha]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd C:\Users\USER\Desktop\Aplicaciones\cam
          git pull origin alpha
          docker compose down
          docker compose up -d --build
